/**
 * Static pricing cache - bundled with extension for offline/privacy mode
 *
 * This file is auto-generated by live_data/generate-pricing-cache.ts
 * Run: pnpm generate-pricing-cache
 *
 * When useLivePricingData is false, the extension uses this cached data
 * instead of making external API calls to Helicone and OpenRouter.
 */

export interface CachedProviderData {
  models: string[];
  pricing: Record<string, { inputPerToken: number; outputPerToken: number }>;
}

export interface CachedOpenRouterGroup {
  id: string;
  displayName: string;
  models: string[];
}

export interface CachedPricingData {
  generatedAt: string;
  version: number;
  helicone: Record<string, CachedProviderData>;
  openRouter: {
    groups: CachedOpenRouterGroup[];
    pricing: Record<string, { inputPerToken: number; outputPerToken: number }>;
  };
}

// Cache generated on 2026-01-05 - Update by running: pnpm generate-pricing-cache
export const CACHED_PRICING_DATA: CachedPricingData = {
  generatedAt: '2026-01-05T15:58:10.367Z',
  version: 1,
  helicone: {
    openai: {
      models: [
        'ada',
        'ada-batch',
        'babbage',
        'babbage-batch',
        'chatgpt-4o-latest',
        'chatgpt-4o-latest-batch',
        'codex-mini-latest',
        'codex-mini-latest-batch',
        'curie',
        'curie-batch',
        'davinci',
        'davinci-batch',
        'ft:gpt-3.5-turbo-',
        'ft:gpt-4o-2024-08-06:',
        'ft:gpt-4o-mini-2024-07-18:',
        'gpt-3.5-turbo',
        'gpt-3.5-turbo-0125',
        'gpt-3.5-turbo-0125-batch',
        'gpt-3.5-turbo-0301',
        'gpt-3.5-turbo-0301-batch',
        'gpt-3.5-turbo-0613',
        'gpt-3.5-turbo-0613-batch',
        'gpt-3.5-turbo-1106',
        'gpt-3.5-turbo-1106-batch',
        'gpt-3.5-turbo-16k-0613',
        'gpt-3.5-turbo-16k-0613-batch',
        'gpt-3.5-turbo-batch',
        'gpt-3.5-turbo-instruct',
        'gpt-3.5-turbo-instruct-0914',
        'gpt-3.5-turbo-instruct-0914-batch',
        'gpt-3.5-turbo-instruct-batch',
        'gpt-35-turbo',
        'gpt-35-turbo-16k',
        'gpt-35-turbo-16k-0613',
        'gpt-35-turbo-16k-0613-batch',
        'gpt-35-turbo-16k-batch',
        'gpt-35-turbo-batch',
        'gpt-4',
        'gpt-4-0125-preview',
        'gpt-4-0125-preview-batch',
        'gpt-4-0314',
        'gpt-4-0314-batch',
        'gpt-4-0613',
        'gpt-4-0613-batch',
        'gpt-4-1106-preview',
        'gpt-4-1106-preview-batch',
        'gpt-4-1106-vision-preview',
        'gpt-4-1106-vision-preview-batch',
        'gpt-4-32k',
        'gpt-4-32k-0314',
        'gpt-4-32k-0314-batch',
        'gpt-4-32k-0613',
        'gpt-4-32k-0613-batch',
        'gpt-4-32k-batch',
        'gpt-4-batch',
        'gpt-4-turbo',
        'gpt-4-turbo-0125-preview',
        'gpt-4-turbo-0125-preview-batch',
        'gpt-4-turbo-2024-04-09',
        'gpt-4-turbo-2024-04-09-batch',
        'gpt-4-turbo-batch',
        'gpt-4-vision-preview',
        'gpt-4-vision-preview-batch',
        'gpt-4.1',
        'gpt-4.1-2025-04-14',
        'gpt-4.1-2025-04-14-batch',
        'gpt-4.1-batch',
        'gpt-4.1-mini',
        'gpt-4.1-mini-2025-04-14',
        'gpt-4.1-mini-2025-04-14-batch',
        'gpt-4.1-mini-batch',
        'gpt-4.1-nano',
        'gpt-4.1-nano-2025-04-14',
        'gpt-4.1-nano-2025-04-14-batch',
        'gpt-4.1-nano-batch',
        'gpt-4o',
        'gpt-4o-2024-05-13',
        'gpt-4o-2024-05-13-batch',
        'gpt-4o-2024-08-06',
        'gpt-4o-2024-08-06-batch',
        'gpt-4o-2024-11-20',
        'gpt-4o-2024-11-20-batch',
        'gpt-4o-batch',
        'gpt-4o-mini',
        'gpt-4o-mini-2024-07-18',
        'gpt-4o-mini-2024-07-18-batch',
        'gpt-4o-mini-2024-07-18.ft-',
        'gpt-4o-mini-batch',
        'gpt-4o-mini-realtime',
        'gpt-4o-mini-realtime-batch',
        'gpt-4o-realtime',
        'gpt-4o-realtime-batch',
        'gpt-4o-search-preview',
        'gpt-4o-search-preview-batch',
        'gpt-5',
        'gpt-5-2025-08-07',
        'gpt-5-2025-08-07-batch',
        'gpt-5-batch',
        'gpt-5-chat-latest',
        'gpt-5-chat-latest-batch',
        'gpt-5-mini',
        'gpt-5-mini-2025-08-07',
        'gpt-5-mini-2025-08-07-batch',
        'gpt-5-mini-batch',
        'gpt-5-nano',
        'gpt-5-nano-2025-08-07',
        'gpt-5-nano-2025-08-07-batch',
        'gpt-5-nano-batch',
        'gpt-5.1',
        'gpt-5.1-batch',
        'gpt-5.1-chat-latest',
        'gpt-5.1-chat-latest-batch',
        'gpt-5.1-codex',
        'gpt-5.1-codex-batch',
        'gpt-5.1-codex-mini',
        'gpt-5.1-codex-mini-batch',
        'gpt-5.2',
        'gpt-5.2-2025-12-11',
        'gpt-5.2-2025-12-11-batch',
        'gpt-5.2-batch',
        'gpt-5.2-chat-latest',
        'gpt-5.2-chat-latest-batch',
        'gpt-5.2-pro',
        'gpt-5.2-pro-batch',
        'o1',
        'o1-2024-12-17',
        'o1-2024-12-17-batch',
        'o1-batch',
        'o1-mini',
        'o1-mini-2024-09-12',
        'o1-mini-2024-09-12-batch',
        'o1-mini-batch',
        'o1-preview',
        'o1-preview-2024-09-12',
        'o1-preview-2024-09-12-batch',
        'o1-preview-batch',
        'o1-pro',
        'o1-pro-batch',
        'o3-2025-04-16',
        'o3-2025-04-16-batch',
        'o3-mini',
        'o3-mini-2025-01-31',
        'o3-mini-2025-01-31-batch',
        'o3-mini-batch',
        'o3-pro',
        'o3-pro-batch',
        'o4-mini',
        'o4-mini-2025-04-16',
        'o4-mini-2025-04-16-batch',
        'o4-mini-batch',
        'openai/gpt-4o-mini-search-preview',
        'openai/gpt-4o-mini-search-preview-batch',
        'text-ada-001',
        'text-ada-001-batch',
        'text-curie-001',
        'text-curie-001-batch',
        'text-davinci-001',
        'text-davinci-001-batch',
        'text-davinci-002',
        'text-davinci-002-batch',
        'text-davinci-003',
        'text-davinci-003-batch',
        'text-embedding-3-large',
        'text-embedding-3-large-batch',
        'text-embedding-3-small',
        'text-embedding-3-small-batch',
        'text-embedding-ada',
        'text-embedding-ada-002',
        'text-embedding-ada-002-batch',
        'text-embedding-ada-002-v2',
        'text-embedding-ada-002-v2-batch',
        'text-embedding-ada-batch',
      ],
      pricing: {
        ada: {
          inputPerToken: 4.0000000000000003e-7,
          outputPerToken: 4.0000000000000003e-7,
        },
        'ada-batch': {
          inputPerToken: 2.0000000000000002e-7,
          outputPerToken: 2.0000000000000002e-7,
        },
        babbage: {
          inputPerToken: 5e-7,
          outputPerToken: 5e-7,
        },
        'babbage-batch': {
          inputPerToken: 2.5e-7,
          outputPerToken: 2.5e-7,
        },
        'chatgpt-4o-latest': {
          inputPerToken: 0.000005,
          outputPerToken: 0.000015,
        },
        'chatgpt-4o-latest-batch': {
          inputPerToken: 0.0000025,
          outputPerToken: 0.0000075,
        },
        'codex-mini-latest': {
          inputPerToken: 0.0000015,
          outputPerToken: 0.000006,
        },
        'codex-mini-latest-batch': {
          inputPerToken: 7.5e-7,
          outputPerToken: 0.000003,
        },
        curie: {
          inputPerToken: 0.000002,
          outputPerToken: 0.000002,
        },
        'curie-batch': {
          inputPerToken: 0.000001,
          outputPerToken: 0.000001,
        },
        davinci: {
          inputPerToken: 0.00002,
          outputPerToken: 0.00002,
        },
        'davinci-batch': {
          inputPerToken: 0.00001,
          outputPerToken: 0.00001,
        },
        'ft:gpt-3.5-turbo-': {
          inputPerToken: 0.000003,
          outputPerToken: 0.000006,
        },
        'ft:gpt-4o-2024-08-06:': {
          inputPerToken: 0.00000375,
          outputPerToken: 0.000015,
        },
        'ft:gpt-4o-mini-2024-07-18:': {
          inputPerToken: 3e-7,
          outputPerToken: 0.0000012,
        },
        'gpt-3.5-turbo': {
          inputPerToken: 0.0000015,
          outputPerToken: 0.000002,
        },
        'gpt-3.5-turbo-0125': {
          inputPerToken: 5e-7,
          outputPerToken: 0.0000015,
        },
        'gpt-3.5-turbo-0125-batch': {
          inputPerToken: 2.5e-7,
          outputPerToken: 7.5e-7,
        },
        'gpt-3.5-turbo-0301': {
          inputPerToken: 0.0000015,
          outputPerToken: 0.000002,
        },
        'gpt-3.5-turbo-0301-batch': {
          inputPerToken: 7.5e-7,
          outputPerToken: 0.000001,
        },
        'gpt-3.5-turbo-0613': {
          inputPerToken: 0.0000015,
          outputPerToken: 0.000002,
        },
        'gpt-3.5-turbo-0613-batch': {
          inputPerToken: 7.5e-7,
          outputPerToken: 0.000001,
        },
        'gpt-3.5-turbo-1106': {
          inputPerToken: 0.000001,
          outputPerToken: 0.000002,
        },
        'gpt-3.5-turbo-1106-batch': {
          inputPerToken: 5e-7,
          outputPerToken: 0.000001,
        },
        'gpt-3.5-turbo-16k-0613': {
          inputPerToken: 0.000003,
          outputPerToken: 0.000004,
        },
        'gpt-3.5-turbo-16k-0613-batch': {
          inputPerToken: 0.0000015,
          outputPerToken: 0.000002,
        },
        'gpt-3.5-turbo-batch': {
          inputPerToken: 7.5e-7,
          outputPerToken: 0.000001,
        },
        'gpt-3.5-turbo-instruct': {
          inputPerToken: 0.0000015,
          outputPerToken: 0.000002,
        },
        'gpt-3.5-turbo-instruct-0914': {
          inputPerToken: 0.0000015,
          outputPerToken: 0.000002,
        },
        'gpt-3.5-turbo-instruct-0914-batch': {
          inputPerToken: 7.5e-7,
          outputPerToken: 0.000001,
        },
        'gpt-3.5-turbo-instruct-batch': {
          inputPerToken: 7.5e-7,
          outputPerToken: 0.000001,
        },
        'gpt-35-turbo': {
          inputPerToken: 0.0000015,
          outputPerToken: 0.000002,
        },
        'gpt-35-turbo-16k': {
          inputPerToken: 0.000003,
          outputPerToken: 0.000004,
        },
        'gpt-35-turbo-16k-0613': {
          inputPerToken: 0.000003,
          outputPerToken: 0.000004,
        },
        'gpt-35-turbo-16k-0613-batch': {
          inputPerToken: 0.0000015,
          outputPerToken: 0.000002,
        },
        'gpt-35-turbo-16k-batch': {
          inputPerToken: 0.0000015,
          outputPerToken: 0.000002,
        },
        'gpt-35-turbo-batch': {
          inputPerToken: 7.5e-7,
          outputPerToken: 0.000001,
        },
        'gpt-4': {
          inputPerToken: 0.00003,
          outputPerToken: 0.00006,
        },
        'gpt-4-0125-preview': {
          inputPerToken: 0.00001,
          outputPerToken: 0.00003,
        },
        'gpt-4-0125-preview-batch': {
          inputPerToken: 0.000005,
          outputPerToken: 0.000015,
        },
        'gpt-4-0314': {
          inputPerToken: 0.00003,
          outputPerToken: 0.00006,
        },
        'gpt-4-0314-batch': {
          inputPerToken: 0.000015,
          outputPerToken: 0.00003,
        },
        'gpt-4-0613': {
          inputPerToken: 0.00003,
          outputPerToken: 0.00006,
        },
        'gpt-4-0613-batch': {
          inputPerToken: 0.000015,
          outputPerToken: 0.00003,
        },
        'gpt-4-1106-preview': {
          inputPerToken: 0.00001,
          outputPerToken: 0.00003,
        },
        'gpt-4-1106-preview-batch': {
          inputPerToken: 0.000005,
          outputPerToken: 0.000015,
        },
        'gpt-4-1106-vision-preview': {
          inputPerToken: 0.00001,
          outputPerToken: 0.00003,
        },
        'gpt-4-1106-vision-preview-batch': {
          inputPerToken: 0.000005,
          outputPerToken: 0.000015,
        },
        'gpt-4-32k': {
          inputPerToken: 0.00006,
          outputPerToken: 0.00012,
        },
        'gpt-4-32k-0314': {
          inputPerToken: 0.00006,
          outputPerToken: 0.00012,
        },
        'gpt-4-32k-0314-batch': {
          inputPerToken: 0.00003,
          outputPerToken: 0.00006,
        },
        'gpt-4-32k-0613': {
          inputPerToken: 0.00006,
          outputPerToken: 0.00012,
        },
        'gpt-4-32k-0613-batch': {
          inputPerToken: 0.00003,
          outputPerToken: 0.00006,
        },
        'gpt-4-32k-batch': {
          inputPerToken: 0.00003,
          outputPerToken: 0.00006,
        },
        'gpt-4-batch': {
          inputPerToken: 0.000015,
          outputPerToken: 0.00003,
        },
        'gpt-4-turbo': {
          inputPerToken: 0.00001,
          outputPerToken: 0.00003,
        },
        'gpt-4-turbo-0125-preview': {
          inputPerToken: 0.00001,
          outputPerToken: 0.00003,
        },
        'gpt-4-turbo-0125-preview-batch': {
          inputPerToken: 0.000005,
          outputPerToken: 0.000015,
        },
        'gpt-4-turbo-2024-04-09': {
          inputPerToken: 0.00001,
          outputPerToken: 0.00003,
        },
        'gpt-4-turbo-2024-04-09-batch': {
          inputPerToken: 0.000005,
          outputPerToken: 0.000015,
        },
        'gpt-4-turbo-batch': {
          inputPerToken: 0.000005,
          outputPerToken: 0.000015,
        },
        'gpt-4-vision-preview': {
          inputPerToken: 0.00001,
          outputPerToken: 0.00003,
        },
        'gpt-4-vision-preview-batch': {
          inputPerToken: 0.000005,
          outputPerToken: 0.000015,
        },
        'gpt-4.1': {
          inputPerToken: 0.000002,
          outputPerToken: 0.000008,
        },
        'gpt-4.1-2025-04-14': {
          inputPerToken: 0.000002,
          outputPerToken: 0.000008,
        },
        'gpt-4.1-2025-04-14-batch': {
          inputPerToken: 0.000001,
          outputPerToken: 0.000004,
        },
        'gpt-4.1-batch': {
          inputPerToken: 0.000001,
          outputPerToken: 0.000004,
        },
        'gpt-4.1-mini': {
          inputPerToken: 4.0000000000000003e-7,
          outputPerToken: 0.0000016000000000000001,
        },
        'gpt-4.1-mini-2025-04-14': {
          inputPerToken: 4.0000000000000003e-7,
          outputPerToken: 0.0000016000000000000001,
        },
        'gpt-4.1-mini-2025-04-14-batch': {
          inputPerToken: 2.0000000000000002e-7,
          outputPerToken: 8.000000000000001e-7,
        },
        'gpt-4.1-mini-batch': {
          inputPerToken: 2.0000000000000002e-7,
          outputPerToken: 8.000000000000001e-7,
        },
        'gpt-4.1-nano': {
          inputPerToken: 1.0000000000000001e-7,
          outputPerToken: 4.0000000000000003e-7,
        },
        'gpt-4.1-nano-2025-04-14': {
          inputPerToken: 1.0000000000000001e-7,
          outputPerToken: 4.0000000000000003e-7,
        },
        'gpt-4.1-nano-2025-04-14-batch': {
          inputPerToken: 5.0000000000000004e-8,
          outputPerToken: 2.0000000000000002e-7,
        },
        'gpt-4.1-nano-batch': {
          inputPerToken: 5.0000000000000004e-8,
          outputPerToken: 2.0000000000000002e-7,
        },
        'gpt-4o': {
          inputPerToken: 0.0000025,
          outputPerToken: 0.00001,
        },
        'gpt-4o-2024-05-13': {
          inputPerToken: 0.000005,
          outputPerToken: 0.000015,
        },
        'gpt-4o-2024-05-13-batch': {
          inputPerToken: 0.0000025,
          outputPerToken: 0.0000075,
        },
        'gpt-4o-2024-08-06': {
          inputPerToken: 0.0000025,
          outputPerToken: 0.00001,
        },
        'gpt-4o-2024-08-06-batch': {
          inputPerToken: 0.00000125,
          outputPerToken: 0.000005,
        },
        'gpt-4o-2024-11-20': {
          inputPerToken: 0.0000025,
          outputPerToken: 0.00001,
        },
        'gpt-4o-2024-11-20-batch': {
          inputPerToken: 0.00000125,
          outputPerToken: 0.000005,
        },
        'gpt-4o-batch': {
          inputPerToken: 0.00000125,
          outputPerToken: 0.000005,
        },
        'gpt-4o-mini': {
          inputPerToken: 1.5e-7,
          outputPerToken: 6e-7,
        },
        'gpt-4o-mini-2024-07-18': {
          inputPerToken: 1.5e-7,
          outputPerToken: 6e-7,
        },
        'gpt-4o-mini-2024-07-18-batch': {
          inputPerToken: 7.5e-8,
          outputPerToken: 3e-7,
        },
        'gpt-4o-mini-2024-07-18.ft-': {
          inputPerToken: 3e-7,
          outputPerToken: 0.0000012,
        },
        'gpt-4o-mini-batch': {
          inputPerToken: 7.5e-8,
          outputPerToken: 3e-7,
        },
        'gpt-4o-mini-realtime': {
          inputPerToken: 6e-7,
          outputPerToken: 0.0000024,
        },
        'gpt-4o-mini-realtime-batch': {
          inputPerToken: 3e-7,
          outputPerToken: 0.0000012,
        },
        'gpt-4o-realtime': {
          inputPerToken: 0.000004,
          outputPerToken: 0.000016,
        },
        'gpt-4o-realtime-batch': {
          inputPerToken: 0.000002,
          outputPerToken: 0.000008,
        },
        'gpt-4o-search-preview': {
          inputPerToken: 0.0000025,
          outputPerToken: 0.00001,
        },
        'gpt-4o-search-preview-batch': {
          inputPerToken: 0.00000125,
          outputPerToken: 0.000005,
        },
        'gpt-5': {
          inputPerToken: 0.00000125,
          outputPerToken: 0.00001,
        },
        'gpt-5-2025-08-07': {
          inputPerToken: 0.00000125,
          outputPerToken: 0.00001,
        },
        'gpt-5-2025-08-07-batch': {
          inputPerToken: 6.25e-7,
          outputPerToken: 0.000005,
        },
        'gpt-5-batch': {
          inputPerToken: 6.25e-7,
          outputPerToken: 0.000005,
        },
        'gpt-5-chat-latest': {
          inputPerToken: 0.00000125,
          outputPerToken: 0.00001,
        },
        'gpt-5-chat-latest-batch': {
          inputPerToken: 6.25e-7,
          outputPerToken: 0.000005,
        },
        'gpt-5-mini': {
          inputPerToken: 2.5e-7,
          outputPerToken: 0.000002,
        },
        'gpt-5-mini-2025-08-07': {
          inputPerToken: 2.5e-7,
          outputPerToken: 0.000002,
        },
        'gpt-5-mini-2025-08-07-batch': {
          inputPerToken: 1.25e-7,
          outputPerToken: 0.000001,
        },
        'gpt-5-mini-batch': {
          inputPerToken: 1.25e-7,
          outputPerToken: 0.000001,
        },
        'gpt-5-nano': {
          inputPerToken: 5.0000000000000004e-8,
          outputPerToken: 4.0000000000000003e-7,
        },
        'gpt-5-nano-2025-08-07': {
          inputPerToken: 5.0000000000000004e-8,
          outputPerToken: 4.0000000000000003e-7,
        },
        'gpt-5-nano-2025-08-07-batch': {
          inputPerToken: 2.5000000000000002e-8,
          outputPerToken: 2.0000000000000002e-7,
        },
        'gpt-5-nano-batch': {
          inputPerToken: 2.5000000000000002e-8,
          outputPerToken: 2.0000000000000002e-7,
        },
        'gpt-5.1': {
          inputPerToken: 0.00000125,
          outputPerToken: 0.00001,
        },
        'gpt-5.1-batch': {
          inputPerToken: 6.25e-7,
          outputPerToken: 0.000005,
        },
        'gpt-5.1-chat-latest': {
          inputPerToken: 0.00000125,
          outputPerToken: 0.00001,
        },
        'gpt-5.1-chat-latest-batch': {
          inputPerToken: 6.25e-7,
          outputPerToken: 0.000005,
        },
        'gpt-5.1-codex': {
          inputPerToken: 0.00000125,
          outputPerToken: 0.00001,
        },
        'gpt-5.1-codex-batch': {
          inputPerToken: 6.25e-7,
          outputPerToken: 0.000005,
        },
        'gpt-5.1-codex-mini': {
          inputPerToken: 2.5e-7,
          outputPerToken: 0.000002,
        },
        'gpt-5.1-codex-mini-batch': {
          inputPerToken: 1.25e-7,
          outputPerToken: 0.000001,
        },
        'gpt-5.2': {
          inputPerToken: 0.00000175,
          outputPerToken: 0.000014,
        },
        'gpt-5.2-2025-12-11': {
          inputPerToken: 0.00000175,
          outputPerToken: 0.000014,
        },
        'gpt-5.2-2025-12-11-batch': {
          inputPerToken: 8.75e-7,
          outputPerToken: 0.000007,
        },
        'gpt-5.2-batch': {
          inputPerToken: 8.75e-7,
          outputPerToken: 0.000007,
        },
        'gpt-5.2-chat-latest': {
          inputPerToken: 0.00000175,
          outputPerToken: 0.000014,
        },
        'gpt-5.2-chat-latest-batch': {
          inputPerToken: 8.75e-7,
          outputPerToken: 0.000007,
        },
        'gpt-5.2-pro': {
          inputPerToken: 0.000021,
          outputPerToken: 0.000168,
        },
        'gpt-5.2-pro-batch': {
          inputPerToken: 0.0000105,
          outputPerToken: 0.000084,
        },
        o1: {
          inputPerToken: 0.000015,
          outputPerToken: 0.00006,
        },
        'o1-2024-12-17': {
          inputPerToken: 0.000015,
          outputPerToken: 0.00006,
        },
        'o1-2024-12-17-batch': {
          inputPerToken: 0.0000075,
          outputPerToken: 0.00003,
        },
        'o1-batch': {
          inputPerToken: 0.0000075,
          outputPerToken: 0.00003,
        },
        'o1-mini': {
          inputPerToken: 0.0000011,
          outputPerToken: 0.0000044,
        },
        'o1-mini-2024-09-12': {
          inputPerToken: 0.0000011,
          outputPerToken: 0.0000044,
        },
        'o1-mini-2024-09-12-batch': {
          inputPerToken: 5.5e-7,
          outputPerToken: 0.0000022,
        },
        'o1-mini-batch': {
          inputPerToken: 5.5e-7,
          outputPerToken: 0.0000022,
        },
        'o1-preview': {
          inputPerToken: 0.000015,
          outputPerToken: 0.00006,
        },
        'o1-preview-2024-09-12': {
          inputPerToken: 0.000015,
          outputPerToken: 0.00006,
        },
        'o1-preview-2024-09-12-batch': {
          inputPerToken: 0.0000075,
          outputPerToken: 0.00003,
        },
        'o1-preview-batch': {
          inputPerToken: 0.0000075,
          outputPerToken: 0.00003,
        },
        'o1-pro': {
          inputPerToken: 0.00015,
          outputPerToken: 0.0006,
        },
        'o1-pro-batch': {
          inputPerToken: 0.000075,
          outputPerToken: 0.0003,
        },
        'o3-2025-04-16': {
          inputPerToken: 0.000002,
          outputPerToken: 0.000008,
        },
        'o3-2025-04-16-batch': {
          inputPerToken: 0.000001,
          outputPerToken: 0.000004,
        },
        'o3-mini': {
          inputPerToken: 0.0000011,
          outputPerToken: 0.0000044,
        },
        'o3-mini-2025-01-31': {
          inputPerToken: 0.0000011,
          outputPerToken: 0.0000044,
        },
        'o3-mini-2025-01-31-batch': {
          inputPerToken: 5.5e-7,
          outputPerToken: 0.0000022,
        },
        'o3-mini-batch': {
          inputPerToken: 5.5e-7,
          outputPerToken: 0.0000022,
        },
        'o3-pro': {
          inputPerToken: 0.00002,
          outputPerToken: 0.00008,
        },
        'o3-pro-batch': {
          inputPerToken: 0.00001,
          outputPerToken: 0.00004,
        },
        'o4-mini': {
          inputPerToken: 0.0000011,
          outputPerToken: 0.0000044,
        },
        'o4-mini-2025-04-16': {
          inputPerToken: 0.0000011,
          outputPerToken: 0.0000044,
        },
        'o4-mini-2025-04-16-batch': {
          inputPerToken: 5.5e-7,
          outputPerToken: 0.0000022,
        },
        'o4-mini-batch': {
          inputPerToken: 5.5e-7,
          outputPerToken: 0.0000022,
        },
        'openai/gpt-4o-mini-search-preview': {
          inputPerToken: 1.5e-7,
          outputPerToken: 6e-7,
        },
        'openai/gpt-4o-mini-search-preview-batch': {
          inputPerToken: 7.5e-8,
          outputPerToken: 3e-7,
        },
        'text-ada-001': {
          inputPerToken: 4.0000000000000003e-7,
          outputPerToken: 4.0000000000000003e-7,
        },
        'text-ada-001-batch': {
          inputPerToken: 2.0000000000000002e-7,
          outputPerToken: 2.0000000000000002e-7,
        },
        'text-curie-001': {
          inputPerToken: 0.000002,
          outputPerToken: 0.000002,
        },
        'text-curie-001-batch': {
          inputPerToken: 0.000001,
          outputPerToken: 0.000001,
        },
        'text-davinci-001': {
          inputPerToken: 0.00002,
          outputPerToken: 0.00002,
        },
        'text-davinci-001-batch': {
          inputPerToken: 0.00001,
          outputPerToken: 0.00001,
        },
        'text-davinci-002': {
          inputPerToken: 0.00002,
          outputPerToken: 0.00002,
        },
        'text-davinci-002-batch': {
          inputPerToken: 0.00001,
          outputPerToken: 0.00001,
        },
        'text-davinci-003': {
          inputPerToken: 0.00002,
          outputPerToken: 0.00002,
        },
        'text-davinci-003-batch': {
          inputPerToken: 0.00001,
          outputPerToken: 0.00001,
        },
        'text-embedding-3-large': {
          inputPerToken: 1.3e-7,
          outputPerToken: 0,
        },
        'text-embedding-3-large-batch': {
          inputPerToken: 6.5e-8,
          outputPerToken: 0,
        },
        'text-embedding-3-small': {
          inputPerToken: 2e-8,
          outputPerToken: 0,
        },
        'text-embedding-3-small-batch': {
          inputPerToken: 1e-8,
          outputPerToken: 0,
        },
        'text-embedding-ada': {
          inputPerToken: 1.0000000000000001e-7,
          outputPerToken: 0,
        },
        'text-embedding-ada-002': {
          inputPerToken: 1.0000000000000001e-7,
          outputPerToken: 0,
        },
        'text-embedding-ada-002-batch': {
          inputPerToken: 5.0000000000000004e-8,
          outputPerToken: 0,
        },
        'text-embedding-ada-002-v2': {
          inputPerToken: 1.0000000000000001e-7,
          outputPerToken: 0,
        },
        'text-embedding-ada-002-v2-batch': {
          inputPerToken: 5.0000000000000004e-8,
          outputPerToken: 0,
        },
        'text-embedding-ada-batch': {
          inputPerToken: 5.0000000000000004e-8,
          outputPerToken: 0,
        },
      },
    },
    anthropic: {
      models: [
        'claude-2',
        'claude-2.0',
        'claude-3-5-haiku-20241022',
        'claude-3-5-sonnet-20240620',
        'claude-3-5-sonnet-20241022',
        'claude-3-7-sonnet-20250219',
        'claude-3-haiku-20240307',
        'claude-3-opus-20240229',
        'claude-3-sonnet-20240229',
        'claude-haiku-4-5-20251001',
        'claude-instant-1',
        'claude-instant-1.2',
        'claude-opus-4-1-20250805',
        'claude-opus-4-20250514',
        'claude-opus-4-5',
        'claude-sonnet-4-20250514',
        'claude-sonnet-4-5-20250929',
        'claude-v1',
      ],
      pricing: {
        'claude-2': {
          inputPerToken: 0.000008,
          outputPerToken: 0.000024,
        },
        'claude-2.0': {
          inputPerToken: 0.00001102,
          outputPerToken: 0.00003268,
        },
        'claude-3-5-haiku-20241022': {
          inputPerToken: 8.000000000000001e-7,
          outputPerToken: 0.000004,
        },
        'claude-3-5-sonnet-20240620': {
          inputPerToken: 0.000003,
          outputPerToken: 0.000015,
        },
        'claude-3-5-sonnet-20241022': {
          inputPerToken: 0.000003,
          outputPerToken: 0.000015,
        },
        'claude-3-7-sonnet-20250219': {
          inputPerToken: 0.000003,
          outputPerToken: 0.000015,
        },
        'claude-3-haiku-20240307': {
          inputPerToken: 2.5e-7,
          outputPerToken: 0.00000125,
        },
        'claude-3-opus-20240229': {
          inputPerToken: 0.000015,
          outputPerToken: 0.000075,
        },
        'claude-3-sonnet-20240229': {
          inputPerToken: 0.000003,
          outputPerToken: 0.000015,
        },
        'claude-haiku-4-5-20251001': {
          inputPerToken: 0.000001,
          outputPerToken: 0.000005,
        },
        'claude-instant-1': {
          inputPerToken: 0.0000016299999999999999,
          outputPerToken: 0.000055100000000000004,
        },
        'claude-instant-1.2': {
          inputPerToken: 0.0000016299999999999999,
          outputPerToken: 0.00000551,
        },
        'claude-opus-4-1-20250805': {
          inputPerToken: 0.000015,
          outputPerToken: 0.000075,
        },
        'claude-opus-4-20250514': {
          inputPerToken: 0.000015,
          outputPerToken: 0.000075,
        },
        'claude-opus-4-5': {
          inputPerToken: 0.000005,
          outputPerToken: 0.000025,
        },
        'claude-sonnet-4-20250514': {
          inputPerToken: 0.000003,
          outputPerToken: 0.000015,
        },
        'claude-sonnet-4-5-20250929': {
          inputPerToken: 0.000003,
          outputPerToken: 0.000015,
        },
        'claude-v1': {
          inputPerToken: 0.000008,
          outputPerToken: 0.000024,
        },
      },
    },
    gemini: {
      models: [
        'claude-3-5-haiku',
        'claude-3-5-sonnet',
        'claude-3-7-sonnet',
        'claude-3-opus',
        'gemini-1.0-pro',
        'gemini-1.0-pro-vision-001',
        'gemini-1.5-flash',
        'gemini-1.5-pro',
        'gemini-2.0-flash',
        'gemini-2.0-flash-lite',
        'gemini-2.5-flash',
        'gemini-2.5-flash-image',
        'gemini-2.5-flash-lite',
        'gemini-2.5-flash-lite-preview-06-17',
        'gemini-2.5-flash-preview',
        'gemini-2.5-flash-preview-image',
        'gemini-2.5-pro',
        'gemini-2.5-pro-exp-03-25',
        'gemini-2.5-pro-preview',
        'gemini-3-flash-preview',
        'gemini-3-pro-preview',
        'gemini-flash-1.5-8b',
        'gemini-pro',
      ],
      pricing: {
        'claude-3-5-haiku': {
          inputPerToken: 8.000000000000001e-7,
          outputPerToken: 0.000004,
        },
        'claude-3-5-sonnet': {
          inputPerToken: 0.000003,
          outputPerToken: 0.000015,
        },
        'claude-3-7-sonnet': {
          inputPerToken: 0.000003,
          outputPerToken: 0.000015,
        },
        'claude-3-opus': {
          inputPerToken: 0.000015,
          outputPerToken: 0.000075,
        },
        'gemini-1.0-pro': {
          inputPerToken: 1.25e-7,
          outputPerToken: 3.75e-7,
        },
        'gemini-1.0-pro-vision-001': {
          inputPerToken: 1.25e-7,
          outputPerToken: 3.75e-7,
        },
        'gemini-1.5-flash': {
          inputPerToken: 3.5e-7,
          outputPerToken: 0.0000010500000000000001,
        },
        'gemini-1.5-pro': {
          inputPerToken: 0.0000035,
          outputPerToken: 0.0000105,
        },
        'gemini-2.0-flash': {
          inputPerToken: 1.0000000000000001e-7,
          outputPerToken: 4.0000000000000003e-7,
        },
        'gemini-2.0-flash-lite': {
          inputPerToken: 7.5e-8,
          outputPerToken: 3e-7,
        },
        'gemini-2.5-flash': {
          inputPerToken: 3e-7,
          outputPerToken: 0.0000025,
        },
        'gemini-2.5-flash-image': {
          inputPerToken: 3e-7,
          outputPerToken: 0.0000025,
        },
        'gemini-2.5-flash-lite': {
          inputPerToken: 1.0000000000000001e-7,
          outputPerToken: 4.0000000000000003e-7,
        },
        'gemini-2.5-flash-lite-preview-06-17': {
          inputPerToken: 1.0000000000000001e-7,
          outputPerToken: 4.0000000000000003e-7,
        },
        'gemini-2.5-flash-preview': {
          inputPerToken: 1.5e-7,
          outputPerToken: 6e-7,
        },
        'gemini-2.5-flash-preview-image': {
          inputPerToken: 3e-7,
          outputPerToken: 0.0000025,
        },
        'gemini-2.5-pro': {
          inputPerToken: 0.00000125,
          outputPerToken: 0.00001,
        },
        'gemini-2.5-pro-exp-03-25': {
          inputPerToken: 0,
          outputPerToken: 0,
        },
        'gemini-2.5-pro-preview': {
          inputPerToken: 0.00000125,
          outputPerToken: 0.00001,
        },
        'gemini-3-flash-preview': {
          inputPerToken: 5e-7,
          outputPerToken: 0.000003,
        },
        'gemini-3-pro-preview': {
          inputPerToken: 0.000002,
          outputPerToken: 0.000012,
        },
        'gemini-flash-1.5-8b': {
          inputPerToken: 3.75e-8,
          outputPerToken: 1.5e-7,
        },
        'gemini-pro': {
          inputPerToken: 1.25e-7,
          outputPerToken: 3.75e-7,
        },
      },
    },
    grok: {
      models: [
        'grok-2-1212',
        'grok-2-vision-1212',
        'grok-3',
        'grok-3-mini',
        'grok-4',
        'grok-4-fast',
        'grok-beta',
        'grok-code-fast-1',
        'grok-vision-beta',
      ],
      pricing: {
        'grok-2-1212': {
          inputPerToken: 0.000002,
          outputPerToken: 0.00001,
        },
        'grok-2-vision-1212': {
          inputPerToken: 0.000002,
          outputPerToken: 0.00001,
        },
        'grok-3': {
          inputPerToken: 0.000003,
          outputPerToken: 0.000015,
        },
        'grok-3-mini': {
          inputPerToken: 3e-7,
          outputPerToken: 5e-7,
        },
        'grok-4': {
          inputPerToken: 0.000003,
          outputPerToken: 0.000015,
        },
        'grok-4-fast': {
          inputPerToken: 2.0000000000000002e-7,
          outputPerToken: 5e-7,
        },
        'grok-beta': {
          inputPerToken: 0.000005,
          outputPerToken: 0.000015,
        },
        'grok-code-fast-1': {
          inputPerToken: 2.0000000000000002e-7,
          outputPerToken: 0.0000015,
        },
        'grok-vision-beta': {
          inputPerToken: 0.000005,
          outputPerToken: 0.000015,
        },
      },
    },
  },
  openRouter: {
    groups: [
      {
        id: 'ai21',
        displayName: 'Ai21',
        models: ['ai21/jamba-large-1.7', 'ai21/jamba-mini-1.7'],
      },
      {
        id: 'aion-labs',
        displayName: 'Aion-labs',
        models: ['aion-labs/aion-1.0', 'aion-labs/aion-1.0-mini', 'aion-labs/aion-rp-llama-3.1-8b'],
      },
      {
        id: 'alfredpros',
        displayName: 'Alfredpros',
        models: ['alfredpros/codellama-7b-instruct-solidity'],
      },
      {
        id: 'alibaba',
        displayName: 'Alibaba',
        models: ['alibaba/tongyi-deepresearch-30b-a3b'],
      },
      {
        id: 'allenai',
        displayName: 'Allenai',
        models: ['allenai/olmo-2-0325-32b-instruct', 'allenai/olmo-3-7b-instruct', 'allenai/olmo-3-7b-think'],
      },
      {
        id: 'alpindale',
        displayName: 'Alpindale',
        models: ['alpindale/goliath-120b'],
      },
      {
        id: 'amazon',
        displayName: 'Amazon',
        models: [
          'amazon/nova-2-lite-v1',
          'amazon/nova-lite-v1',
          'amazon/nova-micro-v1',
          'amazon/nova-premier-v1',
          'amazon/nova-pro-v1',
        ],
      },
      {
        id: 'anthracite-org',
        displayName: 'Anthracite-org',
        models: ['anthracite-org/magnum-v4-72b'],
      },
      {
        id: 'anthropic',
        displayName: 'Anthropic',
        models: [
          'anthropic/claude-3-haiku',
          'anthropic/claude-3-opus',
          'anthropic/claude-3.5-haiku',
          'anthropic/claude-3.5-haiku-20241022',
          'anthropic/claude-3.5-sonnet',
          'anthropic/claude-3.7-sonnet',
          'anthropic/claude-3.7-sonnet:thinking',
          'anthropic/claude-haiku-4.5',
          'anthropic/claude-opus-4',
          'anthropic/claude-opus-4.1',
          'anthropic/claude-opus-4.5',
          'anthropic/claude-sonnet-4',
          'anthropic/claude-sonnet-4.5',
        ],
      },
      {
        id: 'arcee-ai',
        displayName: 'Arcee-ai',
        models: [
          'arcee-ai/coder-large',
          'arcee-ai/maestro-reasoning',
          'arcee-ai/spotlight',
          'arcee-ai/trinity-mini',
          'arcee-ai/virtuoso-large',
        ],
      },
      {
        id: 'baidu',
        displayName: 'Baidu',
        models: [
          'baidu/ernie-4.5-21b-a3b',
          'baidu/ernie-4.5-21b-a3b-thinking',
          'baidu/ernie-4.5-300b-a47b',
          'baidu/ernie-4.5-vl-28b-a3b',
          'baidu/ernie-4.5-vl-424b-a47b',
        ],
      },
      {
        id: 'bytedance',
        displayName: 'Bytedance',
        models: ['bytedance/ui-tars-1.5-7b'],
      },
      {
        id: 'bytedance-seed',
        displayName: 'Bytedance-seed',
        models: ['bytedance-seed/seed-1.6', 'bytedance-seed/seed-1.6-flash'],
      },
      {
        id: 'cohere',
        displayName: 'Cohere',
        models: [
          'cohere/command-a',
          'cohere/command-r-08-2024',
          'cohere/command-r-plus-08-2024',
          'cohere/command-r7b-12-2024',
        ],
      },
      {
        id: 'deepcogito',
        displayName: 'Deepcogito',
        models: [
          'deepcogito/cogito-v2-preview-llama-109b-moe',
          'deepcogito/cogito-v2-preview-llama-405b',
          'deepcogito/cogito-v2-preview-llama-70b',
          'deepcogito/cogito-v2.1-671b',
        ],
      },
      {
        id: 'deepseek',
        displayName: 'DeepSeek',
        models: [
          'deepseek/deepseek-chat',
          'deepseek/deepseek-chat-v3-0324',
          'deepseek/deepseek-chat-v3.1',
          'deepseek/deepseek-prover-v2',
          'deepseek/deepseek-r1',
          'deepseek/deepseek-r1-0528',
          'deepseek/deepseek-r1-0528-qwen3-8b',
          'deepseek/deepseek-r1-distill-llama-70b',
          'deepseek/deepseek-r1-distill-qwen-14b',
          'deepseek/deepseek-r1-distill-qwen-32b',
          'deepseek/deepseek-v3.1-terminus',
          'deepseek/deepseek-v3.1-terminus:exacto',
          'deepseek/deepseek-v3.2',
          'deepseek/deepseek-v3.2-exp',
          'deepseek/deepseek-v3.2-speciale',
        ],
      },
      {
        id: 'eleutherai',
        displayName: 'Eleutherai',
        models: ['eleutherai/llemma_7b'],
      },
      {
        id: 'essentialai',
        displayName: 'Essentialai',
        models: ['essentialai/rnj-1-instruct'],
      },
      {
        id: 'google',
        displayName: 'Google',
        models: [
          'google/gemini-2.0-flash-001',
          'google/gemini-2.0-flash-lite-001',
          'google/gemini-2.5-flash',
          'google/gemini-2.5-flash-image',
          'google/gemini-2.5-flash-image-preview',
          'google/gemini-2.5-flash-lite',
          'google/gemini-2.5-flash-lite-preview-09-2025',
          'google/gemini-2.5-flash-preview-09-2025',
          'google/gemini-2.5-pro',
          'google/gemini-2.5-pro-preview',
          'google/gemini-2.5-pro-preview-05-06',
          'google/gemini-3-flash-preview',
          'google/gemini-3-pro-image-preview',
          'google/gemini-3-pro-preview',
          'google/gemma-2-27b-it',
          'google/gemma-2-9b-it',
          'google/gemma-3-12b-it',
          'google/gemma-3-27b-it',
          'google/gemma-3-4b-it',
          'google/gemma-3n-e4b-it',
        ],
      },
      {
        id: 'gryphe',
        displayName: 'Gryphe',
        models: ['gryphe/mythomax-l2-13b'],
      },
      {
        id: 'ibm-granite',
        displayName: 'Ibm-granite',
        models: ['ibm-granite/granite-4.0-h-micro'],
      },
      {
        id: 'inception',
        displayName: 'Inception',
        models: ['inception/mercury', 'inception/mercury-coder'],
      },
      {
        id: 'inflection',
        displayName: 'Inflection',
        models: ['inflection/inflection-3-pi', 'inflection/inflection-3-productivity'],
      },
      {
        id: 'kwaipilot',
        displayName: 'Kwaipilot',
        models: ['kwaipilot/kat-coder-pro'],
      },
      {
        id: 'liquid',
        displayName: 'Liquid',
        models: ['liquid/lfm-2.2-6b', 'liquid/lfm2-8b-a1b'],
      },
      {
        id: 'mancer',
        displayName: 'Mancer',
        models: ['mancer/weaver'],
      },
      {
        id: 'meituan',
        displayName: 'Meituan',
        models: ['meituan/longcat-flash-chat'],
      },
      {
        id: 'meta-llama',
        displayName: 'Meta Llama',
        models: [
          'meta-llama/llama-3-70b-instruct',
          'meta-llama/llama-3-8b-instruct',
          'meta-llama/llama-3.1-405b',
          'meta-llama/llama-3.1-405b-instruct',
          'meta-llama/llama-3.1-70b-instruct',
          'meta-llama/llama-3.1-8b-instruct',
          'meta-llama/llama-3.2-11b-vision-instruct',
          'meta-llama/llama-3.2-1b-instruct',
          'meta-llama/llama-3.2-3b-instruct',
          'meta-llama/llama-3.2-90b-vision-instruct',
          'meta-llama/llama-3.3-70b-instruct',
          'meta-llama/llama-4-maverick',
          'meta-llama/llama-4-scout',
          'meta-llama/llama-guard-2-8b',
          'meta-llama/llama-guard-3-8b',
          'meta-llama/llama-guard-4-12b',
        ],
      },
      {
        id: 'microsoft',
        displayName: 'Microsoft',
        models: [
          'microsoft/phi-3-medium-128k-instruct',
          'microsoft/phi-3-mini-128k-instruct',
          'microsoft/phi-3.5-mini-128k-instruct',
          'microsoft/phi-4',
          'microsoft/phi-4-multimodal-instruct',
          'microsoft/phi-4-reasoning-plus',
          'microsoft/wizardlm-2-8x22b',
        ],
      },
      {
        id: 'minimax',
        displayName: 'Minimax',
        models: ['minimax/minimax-01', 'minimax/minimax-m1', 'minimax/minimax-m2', 'minimax/minimax-m2.1'],
      },
      {
        id: 'mistralai',
        displayName: 'Mistral',
        models: [
          'mistralai/codestral-2508',
          'mistralai/devstral-2512',
          'mistralai/devstral-medium',
          'mistralai/devstral-small',
          'mistralai/devstral-small-2505',
          'mistralai/ministral-14b-2512',
          'mistralai/ministral-3b',
          'mistralai/ministral-3b-2512',
          'mistralai/ministral-8b',
          'mistralai/ministral-8b-2512',
          'mistralai/mistral-7b-instruct',
          'mistralai/mistral-7b-instruct-v0.1',
          'mistralai/mistral-7b-instruct-v0.2',
          'mistralai/mistral-7b-instruct-v0.3',
          'mistralai/mistral-large',
          'mistralai/mistral-large-2407',
          'mistralai/mistral-large-2411',
          'mistralai/mistral-large-2512',
          'mistralai/mistral-medium-3',
          'mistralai/mistral-medium-3.1',
          'mistralai/mistral-nemo',
          'mistralai/mistral-saba',
          'mistralai/mistral-small-24b-instruct-2501',
          'mistralai/mistral-small-3.1-24b-instruct',
          'mistralai/mistral-small-3.2-24b-instruct',
          'mistralai/mistral-small-creative',
          'mistralai/mistral-tiny',
          'mistralai/mixtral-8x22b-instruct',
          'mistralai/mixtral-8x7b-instruct',
          'mistralai/pixtral-12b',
          'mistralai/pixtral-large-2411',
          'mistralai/voxtral-small-24b-2507',
        ],
      },
      {
        id: 'moonshotai',
        displayName: 'Moonshotai',
        models: [
          'moonshotai/kimi-dev-72b',
          'moonshotai/kimi-k2',
          'moonshotai/kimi-k2-0905',
          'moonshotai/kimi-k2-0905:exacto',
          'moonshotai/kimi-k2-thinking',
        ],
      },
      {
        id: 'morph',
        displayName: 'Morph',
        models: ['morph/morph-v3-fast', 'morph/morph-v3-large'],
      },
      {
        id: 'neversleep',
        displayName: 'Neversleep',
        models: ['neversleep/llama-3.1-lumimaid-8b', 'neversleep/noromaid-20b'],
      },
      {
        id: 'nousresearch',
        displayName: 'Nousresearch',
        models: [
          'nousresearch/deephermes-3-mistral-24b-preview',
          'nousresearch/hermes-2-pro-llama-3-8b',
          'nousresearch/hermes-3-llama-3.1-405b',
          'nousresearch/hermes-3-llama-3.1-70b',
          'nousresearch/hermes-4-405b',
          'nousresearch/hermes-4-70b',
        ],
      },
      {
        id: 'nvidia',
        displayName: 'Nvidia',
        models: [
          'nvidia/llama-3.1-nemotron-70b-instruct',
          'nvidia/llama-3.1-nemotron-ultra-253b-v1',
          'nvidia/llama-3.3-nemotron-super-49b-v1.5',
          'nvidia/nemotron-3-nano-30b-a3b',
          'nvidia/nemotron-nano-12b-v2-vl',
          'nvidia/nemotron-nano-9b-v2',
        ],
      },
      {
        id: 'openai',
        displayName: 'OpenAI',
        models: [
          'openai/chatgpt-4o-latest',
          'openai/codex-mini',
          'openai/gpt-3.5-turbo',
          'openai/gpt-3.5-turbo-0613',
          'openai/gpt-3.5-turbo-16k',
          'openai/gpt-3.5-turbo-instruct',
          'openai/gpt-4',
          'openai/gpt-4-0314',
          'openai/gpt-4-1106-preview',
          'openai/gpt-4-turbo',
          'openai/gpt-4-turbo-preview',
          'openai/gpt-4.1',
          'openai/gpt-4.1-mini',
          'openai/gpt-4.1-nano',
          'openai/gpt-4o',
          'openai/gpt-4o-2024-05-13',
          'openai/gpt-4o-2024-08-06',
          'openai/gpt-4o-2024-11-20',
          'openai/gpt-4o-audio-preview',
          'openai/gpt-4o-mini',
          'openai/gpt-4o-mini-2024-07-18',
          'openai/gpt-4o-mini-search-preview',
          'openai/gpt-4o-search-preview',
          'openai/gpt-5',
          'openai/gpt-5-chat',
          'openai/gpt-5-codex',
          'openai/gpt-5-image',
          'openai/gpt-5-image-mini',
          'openai/gpt-5-mini',
          'openai/gpt-5-nano',
          'openai/gpt-5-pro',
          'openai/gpt-5.1',
          'openai/gpt-5.1-chat',
          'openai/gpt-5.1-codex',
          'openai/gpt-5.1-codex-max',
          'openai/gpt-5.1-codex-mini',
          'openai/gpt-5.2',
          'openai/gpt-5.2-chat',
          'openai/gpt-5.2-pro',
          'openai/gpt-oss-120b',
          'openai/gpt-oss-120b:exacto',
          'openai/gpt-oss-20b',
          'openai/gpt-oss-safeguard-20b',
          'openai/o1',
          'openai/o1-pro',
          'openai/o3',
          'openai/o3-deep-research',
          'openai/o3-mini',
          'openai/o3-mini-high',
          'openai/o3-pro',
          'openai/o4-mini',
          'openai/o4-mini-deep-research',
          'openai/o4-mini-high',
        ],
      },
      {
        id: 'opengvlab',
        displayName: 'Opengvlab',
        models: ['opengvlab/internvl3-78b'],
      },
      {
        id: 'openrouter',
        displayName: 'Openrouter',
        models: ['openrouter/auto', 'openrouter/bodybuilder'],
      },
      {
        id: 'perplexity',
        displayName: 'Perplexity',
        models: [
          'perplexity/sonar',
          'perplexity/sonar-deep-research',
          'perplexity/sonar-pro',
          'perplexity/sonar-pro-search',
          'perplexity/sonar-reasoning',
          'perplexity/sonar-reasoning-pro',
        ],
      },
      {
        id: 'prime-intellect',
        displayName: 'Prime-intellect',
        models: ['prime-intellect/intellect-3'],
      },
      {
        id: 'qwen',
        displayName: 'Qwen',
        models: [
          'qwen/qwen-2.5-72b-instruct',
          'qwen/qwen-2.5-7b-instruct',
          'qwen/qwen-2.5-coder-32b-instruct',
          'qwen/qwen-2.5-vl-7b-instruct',
          'qwen/qwen-max',
          'qwen/qwen-plus',
          'qwen/qwen-plus-2025-07-28',
          'qwen/qwen-plus-2025-07-28:thinking',
          'qwen/qwen-turbo',
          'qwen/qwen-vl-max',
          'qwen/qwen-vl-plus',
          'qwen/qwen2.5-coder-7b-instruct',
          'qwen/qwen2.5-vl-32b-instruct',
          'qwen/qwen2.5-vl-72b-instruct',
          'qwen/qwen3-14b',
          'qwen/qwen3-235b-a22b',
          'qwen/qwen3-235b-a22b-2507',
          'qwen/qwen3-235b-a22b-thinking-2507',
          'qwen/qwen3-30b-a3b',
          'qwen/qwen3-30b-a3b-instruct-2507',
          'qwen/qwen3-30b-a3b-thinking-2507',
          'qwen/qwen3-32b',
          'qwen/qwen3-8b',
          'qwen/qwen3-coder',
          'qwen/qwen3-coder-30b-a3b-instruct',
          'qwen/qwen3-coder-flash',
          'qwen/qwen3-coder-plus',
          'qwen/qwen3-coder:exacto',
          'qwen/qwen3-max',
          'qwen/qwen3-next-80b-a3b-instruct',
          'qwen/qwen3-next-80b-a3b-thinking',
          'qwen/qwen3-vl-235b-a22b-instruct',
          'qwen/qwen3-vl-235b-a22b-thinking',
          'qwen/qwen3-vl-30b-a3b-instruct',
          'qwen/qwen3-vl-30b-a3b-thinking',
          'qwen/qwen3-vl-32b-instruct',
          'qwen/qwen3-vl-8b-instruct',
          'qwen/qwen3-vl-8b-thinking',
          'qwen/qwq-32b',
        ],
      },
      {
        id: 'raifle',
        displayName: 'Raifle',
        models: ['raifle/sorcererlm-8x22b'],
      },
      {
        id: 'relace',
        displayName: 'Relace',
        models: ['relace/relace-apply-3', 'relace/relace-search'],
      },
      {
        id: 'sao10k',
        displayName: 'Sao10k',
        models: [
          'sao10k/l3-euryale-70b',
          'sao10k/l3-lunaris-8b',
          'sao10k/l3.1-70b-hanami-x1',
          'sao10k/l3.1-euryale-70b',
          'sao10k/l3.3-euryale-70b',
        ],
      },
      {
        id: 'stepfun-ai',
        displayName: 'Stepfun-ai',
        models: ['stepfun-ai/step3'],
      },
      {
        id: 'switchpoint',
        displayName: 'Switchpoint',
        models: ['switchpoint/router'],
      },
      {
        id: 'tencent',
        displayName: 'Tencent',
        models: ['tencent/hunyuan-a13b-instruct'],
      },
      {
        id: 'thedrummer',
        displayName: 'Thedrummer',
        models: [
          'thedrummer/cydonia-24b-v4.1',
          'thedrummer/rocinante-12b',
          'thedrummer/skyfall-36b-v2',
          'thedrummer/unslopnemo-12b',
        ],
      },
      {
        id: 'thudm',
        displayName: 'Thudm',
        models: ['thudm/glm-4.1v-9b-thinking'],
      },
      {
        id: 'tngtech',
        displayName: 'Tngtech',
        models: ['tngtech/deepseek-r1t-chimera', 'tngtech/deepseek-r1t2-chimera', 'tngtech/tng-r1t-chimera'],
      },
      {
        id: 'undi95',
        displayName: 'Undi95',
        models: ['undi95/remm-slerp-l2-13b'],
      },
      {
        id: 'x-ai',
        displayName: 'xAI',
        models: [
          'x-ai/grok-3',
          'x-ai/grok-3-beta',
          'x-ai/grok-3-mini',
          'x-ai/grok-3-mini-beta',
          'x-ai/grok-4',
          'x-ai/grok-4-fast',
          'x-ai/grok-4.1-fast',
          'x-ai/grok-code-fast-1',
        ],
      },
      {
        id: 'z-ai',
        displayName: 'Z-ai',
        models: [
          'z-ai/glm-4-32b',
          'z-ai/glm-4.5',
          'z-ai/glm-4.5-air',
          'z-ai/glm-4.5v',
          'z-ai/glm-4.6',
          'z-ai/glm-4.6:exacto',
          'z-ai/glm-4.6v',
          'z-ai/glm-4.7',
        ],
      },
    ],
    pricing: {
      'bytedance-seed/seed-1.6-flash': {
        inputPerToken: 7.5e-8,
        outputPerToken: 3e-7,
      },
      'bytedance-seed/seed-1.6': {
        inputPerToken: 2.5e-7,
        outputPerToken: 0.000002,
      },
      'minimax/minimax-m2.1': {
        inputPerToken: 1.2e-7,
        outputPerToken: 4.8e-7,
      },
      'z-ai/glm-4.7': {
        inputPerToken: 1.6e-7,
        outputPerToken: 8e-7,
      },
      'google/gemini-3-flash-preview': {
        inputPerToken: 5e-7,
        outputPerToken: 0.000003,
      },
      'mistralai/mistral-small-creative': {
        inputPerToken: 1e-7,
        outputPerToken: 3e-7,
      },
      'nvidia/nemotron-3-nano-30b-a3b': {
        inputPerToken: 6e-8,
        outputPerToken: 2.4e-7,
      },
      'openai/gpt-5.2-chat': {
        inputPerToken: 0.00000175,
        outputPerToken: 0.000014,
      },
      'openai/gpt-5.2-pro': {
        inputPerToken: 0.000021,
        outputPerToken: 0.000168,
      },
      'openai/gpt-5.2': {
        inputPerToken: 0.00000175,
        outputPerToken: 0.000014,
      },
      'mistralai/devstral-2512': {
        inputPerToken: 5e-8,
        outputPerToken: 2.2e-7,
      },
      'relace/relace-search': {
        inputPerToken: 0.000001,
        outputPerToken: 0.000003,
      },
      'z-ai/glm-4.6v': {
        inputPerToken: 3e-7,
        outputPerToken: 9e-7,
      },
      'essentialai/rnj-1-instruct': {
        inputPerToken: 1.5e-7,
        outputPerToken: 1.5e-7,
      },
      'openrouter/bodybuilder': {
        inputPerToken: -1,
        outputPerToken: -1,
      },
      'openai/gpt-5.1-codex-max': {
        inputPerToken: 0.00000125,
        outputPerToken: 0.00001,
      },
      'amazon/nova-2-lite-v1': {
        inputPerToken: 3e-7,
        outputPerToken: 0.0000025,
      },
      'mistralai/ministral-14b-2512': {
        inputPerToken: 2e-7,
        outputPerToken: 2e-7,
      },
      'mistralai/ministral-8b-2512': {
        inputPerToken: 1.5e-7,
        outputPerToken: 1.5e-7,
      },
      'mistralai/ministral-3b-2512': {
        inputPerToken: 1e-7,
        outputPerToken: 1e-7,
      },
      'mistralai/mistral-large-2512': {
        inputPerToken: 5e-7,
        outputPerToken: 0.0000015,
      },
      'arcee-ai/trinity-mini': {
        inputPerToken: 4.5e-8,
        outputPerToken: 1.5e-7,
      },
      'deepseek/deepseek-v3.2-speciale': {
        inputPerToken: 2.7e-7,
        outputPerToken: 4.1e-7,
      },
      'deepseek/deepseek-v3.2': {
        inputPerToken: 2.5e-7,
        outputPerToken: 3.8e-7,
      },
      'prime-intellect/intellect-3': {
        inputPerToken: 2e-7,
        outputPerToken: 0.0000011,
      },
      'tngtech/tng-r1t-chimera': {
        inputPerToken: 2.5e-7,
        outputPerToken: 8.5e-7,
      },
      'anthropic/claude-opus-4.5': {
        inputPerToken: 0.000005,
        outputPerToken: 0.000025,
      },
      'allenai/olmo-3-7b-instruct': {
        inputPerToken: 1e-7,
        outputPerToken: 2e-7,
      },
      'allenai/olmo-3-7b-think': {
        inputPerToken: 1.2e-7,
        outputPerToken: 2e-7,
      },
      'google/gemini-3-pro-image-preview': {
        inputPerToken: 0.000002,
        outputPerToken: 0.000012,
      },
      'x-ai/grok-4.1-fast': {
        inputPerToken: 2e-7,
        outputPerToken: 5e-7,
      },
      'google/gemini-3-pro-preview': {
        inputPerToken: 0.000002,
        outputPerToken: 0.000012,
      },
      'deepcogito/cogito-v2.1-671b': {
        inputPerToken: 0.00000125,
        outputPerToken: 0.00000125,
      },
      'openai/gpt-5.1': {
        inputPerToken: 0.00000125,
        outputPerToken: 0.00001,
      },
      'openai/gpt-5.1-chat': {
        inputPerToken: 0.00000125,
        outputPerToken: 0.00001,
      },
      'openai/gpt-5.1-codex': {
        inputPerToken: 0.00000125,
        outputPerToken: 0.00001,
      },
      'openai/gpt-5.1-codex-mini': {
        inputPerToken: 2.5e-7,
        outputPerToken: 0.000002,
      },
      'kwaipilot/kat-coder-pro': {
        inputPerToken: 2.07e-7,
        outputPerToken: 8.28e-7,
      },
      'moonshotai/kimi-k2-thinking': {
        inputPerToken: 3.2e-7,
        outputPerToken: 4.8e-7,
      },
      'amazon/nova-premier-v1': {
        inputPerToken: 0.0000025,
        outputPerToken: 0.0000125,
      },
      'perplexity/sonar-pro-search': {
        inputPerToken: 0.000003,
        outputPerToken: 0.000015,
      },
      'mistralai/voxtral-small-24b-2507': {
        inputPerToken: 1e-7,
        outputPerToken: 3e-7,
      },
      'openai/gpt-oss-safeguard-20b': {
        inputPerToken: 7.5e-8,
        outputPerToken: 3e-7,
      },
      'nvidia/nemotron-nano-12b-v2-vl': {
        inputPerToken: 2e-7,
        outputPerToken: 6e-7,
      },
      'minimax/minimax-m2': {
        inputPerToken: 2e-7,
        outputPerToken: 0.000001,
      },
      'qwen/qwen3-vl-32b-instruct': {
        inputPerToken: 5e-7,
        outputPerToken: 0.0000015,
      },
      'liquid/lfm2-8b-a1b': {
        inputPerToken: 5e-8,
        outputPerToken: 1e-7,
      },
      'liquid/lfm-2.2-6b': {
        inputPerToken: 5e-8,
        outputPerToken: 1e-7,
      },
      'ibm-granite/granite-4.0-h-micro': {
        inputPerToken: 1.7e-8,
        outputPerToken: 1.1e-7,
      },
      'deepcogito/cogito-v2-preview-llama-405b': {
        inputPerToken: 0.0000035,
        outputPerToken: 0.0000035,
      },
      'openai/gpt-5-image-mini': {
        inputPerToken: 0.0000025,
        outputPerToken: 0.000002,
      },
      'anthropic/claude-haiku-4.5': {
        inputPerToken: 0.000001,
        outputPerToken: 0.000005,
      },
      'qwen/qwen3-vl-8b-thinking': {
        inputPerToken: 1.8e-7,
        outputPerToken: 0.0000021,
      },
      'qwen/qwen3-vl-8b-instruct': {
        inputPerToken: 8e-8,
        outputPerToken: 5e-7,
      },
      'openai/gpt-5-image': {
        inputPerToken: 0.00001,
        outputPerToken: 0.00001,
      },
      'openai/o3-deep-research': {
        inputPerToken: 0.00001,
        outputPerToken: 0.00004,
      },
      'openai/o4-mini-deep-research': {
        inputPerToken: 0.000002,
        outputPerToken: 0.000008,
      },
      'nvidia/llama-3.3-nemotron-super-49b-v1.5': {
        inputPerToken: 1e-7,
        outputPerToken: 4e-7,
      },
      'baidu/ernie-4.5-21b-a3b-thinking': {
        inputPerToken: 7e-8,
        outputPerToken: 2.8e-7,
      },
      'google/gemini-2.5-flash-image': {
        inputPerToken: 3e-7,
        outputPerToken: 0.0000025,
      },
      'qwen/qwen3-vl-30b-a3b-thinking': {
        inputPerToken: 2e-7,
        outputPerToken: 0.000001,
      },
      'qwen/qwen3-vl-30b-a3b-instruct': {
        inputPerToken: 1.5e-7,
        outputPerToken: 6e-7,
      },
      'openai/gpt-5-pro': {
        inputPerToken: 0.000015,
        outputPerToken: 0.00012,
      },
      'z-ai/glm-4.6': {
        inputPerToken: 3.5e-7,
        outputPerToken: 0.0000015,
      },
      'z-ai/glm-4.6:exacto': {
        inputPerToken: 4.4e-7,
        outputPerToken: 0.00000176,
      },
      'anthropic/claude-sonnet-4.5': {
        inputPerToken: 0.000003,
        outputPerToken: 0.000015,
      },
      'deepseek/deepseek-v3.2-exp': {
        inputPerToken: 2.1e-7,
        outputPerToken: 3.2e-7,
      },
      'thedrummer/cydonia-24b-v4.1': {
        inputPerToken: 3e-7,
        outputPerToken: 5e-7,
      },
      'relace/relace-apply-3': {
        inputPerToken: 8.5e-7,
        outputPerToken: 0.00000125,
      },
      'google/gemini-2.5-flash-preview-09-2025': {
        inputPerToken: 3e-7,
        outputPerToken: 0.0000025,
      },
      'google/gemini-2.5-flash-lite-preview-09-2025': {
        inputPerToken: 1e-7,
        outputPerToken: 4e-7,
      },
      'qwen/qwen3-vl-235b-a22b-thinking': {
        inputPerToken: 4.5e-7,
        outputPerToken: 0.0000035,
      },
      'qwen/qwen3-vl-235b-a22b-instruct': {
        inputPerToken: 1.2e-7,
        outputPerToken: 5.6e-7,
      },
      'qwen/qwen3-max': {
        inputPerToken: 0.0000012,
        outputPerToken: 0.000006,
      },
      'qwen/qwen3-coder-plus': {
        inputPerToken: 0.000001,
        outputPerToken: 0.000005,
      },
      'openai/gpt-5-codex': {
        inputPerToken: 0.00000125,
        outputPerToken: 0.00001,
      },
      'deepseek/deepseek-v3.1-terminus:exacto': {
        inputPerToken: 2.1e-7,
        outputPerToken: 7.9e-7,
      },
      'deepseek/deepseek-v3.1-terminus': {
        inputPerToken: 2.1e-7,
        outputPerToken: 7.9e-7,
      },
      'x-ai/grok-4-fast': {
        inputPerToken: 2e-7,
        outputPerToken: 5e-7,
      },
      'alibaba/tongyi-deepresearch-30b-a3b': {
        inputPerToken: 9e-8,
        outputPerToken: 4e-7,
      },
      'qwen/qwen3-coder-flash': {
        inputPerToken: 3e-7,
        outputPerToken: 0.0000015,
      },
      'opengvlab/internvl3-78b': {
        inputPerToken: 1e-7,
        outputPerToken: 3.9e-7,
      },
      'qwen/qwen3-next-80b-a3b-thinking': {
        inputPerToken: 1.5e-7,
        outputPerToken: 0.0000012,
      },
      'qwen/qwen3-next-80b-a3b-instruct': {
        inputPerToken: 6e-8,
        outputPerToken: 6e-7,
      },
      'meituan/longcat-flash-chat': {
        inputPerToken: 2e-7,
        outputPerToken: 8e-7,
      },
      'qwen/qwen-plus-2025-07-28': {
        inputPerToken: 4e-7,
        outputPerToken: 0.0000012,
      },
      'qwen/qwen-plus-2025-07-28:thinking': {
        inputPerToken: 4e-7,
        outputPerToken: 0.000004,
      },
      'nvidia/nemotron-nano-9b-v2': {
        inputPerToken: 4e-8,
        outputPerToken: 1.6e-7,
      },
      'moonshotai/kimi-k2-0905': {
        inputPerToken: 3.9e-7,
        outputPerToken: 0.0000019,
      },
      'moonshotai/kimi-k2-0905:exacto': {
        inputPerToken: 6e-7,
        outputPerToken: 0.0000025,
      },
      'deepcogito/cogito-v2-preview-llama-70b': {
        inputPerToken: 8.8e-7,
        outputPerToken: 8.8e-7,
      },
      'deepcogito/cogito-v2-preview-llama-109b-moe': {
        inputPerToken: 1.8e-7,
        outputPerToken: 5.9e-7,
      },
      'stepfun-ai/step3': {
        inputPerToken: 5.7e-7,
        outputPerToken: 0.00000142,
      },
      'qwen/qwen3-30b-a3b-thinking-2507': {
        inputPerToken: 5.1e-8,
        outputPerToken: 3.4e-7,
      },
      'x-ai/grok-code-fast-1': {
        inputPerToken: 2e-7,
        outputPerToken: 0.0000015,
      },
      'nousresearch/hermes-4-70b': {
        inputPerToken: 1.1e-7,
        outputPerToken: 3.8e-7,
      },
      'nousresearch/hermes-4-405b': {
        inputPerToken: 0.000001,
        outputPerToken: 0.000003,
      },
      'google/gemini-2.5-flash-image-preview': {
        inputPerToken: 3e-7,
        outputPerToken: 0.0000025,
      },
      'deepseek/deepseek-chat-v3.1': {
        inputPerToken: 1.5e-7,
        outputPerToken: 7.5e-7,
      },
      'openai/gpt-4o-audio-preview': {
        inputPerToken: 0.0000025,
        outputPerToken: 0.00001,
      },
      'mistralai/mistral-medium-3.1': {
        inputPerToken: 4e-7,
        outputPerToken: 0.000002,
      },
      'baidu/ernie-4.5-21b-a3b': {
        inputPerToken: 7e-8,
        outputPerToken: 2.8e-7,
      },
      'baidu/ernie-4.5-vl-28b-a3b': {
        inputPerToken: 1.4e-7,
        outputPerToken: 5.6e-7,
      },
      'z-ai/glm-4.5v': {
        inputPerToken: 6e-7,
        outputPerToken: 0.0000018,
      },
      'ai21/jamba-mini-1.7': {
        inputPerToken: 2e-7,
        outputPerToken: 4e-7,
      },
      'ai21/jamba-large-1.7': {
        inputPerToken: 0.000002,
        outputPerToken: 0.000008,
      },
      'openai/gpt-5-chat': {
        inputPerToken: 0.00000125,
        outputPerToken: 0.00001,
      },
      'openai/gpt-5': {
        inputPerToken: 0.00000125,
        outputPerToken: 0.00001,
      },
      'openai/gpt-5-mini': {
        inputPerToken: 2.5e-7,
        outputPerToken: 0.000002,
      },
      'openai/gpt-5-nano': {
        inputPerToken: 5e-8,
        outputPerToken: 4e-7,
      },
      'openai/gpt-oss-120b': {
        inputPerToken: 2e-8,
        outputPerToken: 1e-7,
      },
      'openai/gpt-oss-120b:exacto': {
        inputPerToken: 3.9e-8,
        outputPerToken: 1.9e-7,
      },
      'openai/gpt-oss-20b': {
        inputPerToken: 1.6e-8,
        outputPerToken: 6e-8,
      },
      'anthropic/claude-opus-4.1': {
        inputPerToken: 0.000015,
        outputPerToken: 0.000075,
      },
      'mistralai/codestral-2508': {
        inputPerToken: 3e-7,
        outputPerToken: 9e-7,
      },
      'qwen/qwen3-coder-30b-a3b-instruct': {
        inputPerToken: 7e-8,
        outputPerToken: 2.7e-7,
      },
      'qwen/qwen3-30b-a3b-instruct-2507': {
        inputPerToken: 8e-8,
        outputPerToken: 3.3e-7,
      },
      'z-ai/glm-4.5': {
        inputPerToken: 3.5e-7,
        outputPerToken: 0.00000155,
      },
      'z-ai/glm-4.5-air': {
        inputPerToken: 5e-8,
        outputPerToken: 2.2e-7,
      },
      'qwen/qwen3-235b-a22b-thinking-2507': {
        inputPerToken: 1.1e-7,
        outputPerToken: 6e-7,
      },
      'z-ai/glm-4-32b': {
        inputPerToken: 1e-7,
        outputPerToken: 1e-7,
      },
      'qwen/qwen3-coder': {
        inputPerToken: 2.2e-7,
        outputPerToken: 9.5e-7,
      },
      'qwen/qwen3-coder:exacto': {
        inputPerToken: 2.2e-7,
        outputPerToken: 0.0000018,
      },
      'bytedance/ui-tars-1.5-7b': {
        inputPerToken: 1e-7,
        outputPerToken: 2e-7,
      },
      'google/gemini-2.5-flash-lite': {
        inputPerToken: 1e-7,
        outputPerToken: 4e-7,
      },
      'qwen/qwen3-235b-a22b-2507': {
        inputPerToken: 7.1e-8,
        outputPerToken: 4.63e-7,
      },
      'switchpoint/router': {
        inputPerToken: 8.5e-7,
        outputPerToken: 0.0000034,
      },
      'moonshotai/kimi-k2': {
        inputPerToken: 5e-7,
        outputPerToken: 0.0000024,
      },
      'thudm/glm-4.1v-9b-thinking': {
        inputPerToken: 3.5e-8,
        outputPerToken: 1.38e-7,
      },
      'mistralai/devstral-medium': {
        inputPerToken: 4e-7,
        outputPerToken: 0.000002,
      },
      'mistralai/devstral-small': {
        inputPerToken: 7e-8,
        outputPerToken: 2.8e-7,
      },
      'x-ai/grok-4': {
        inputPerToken: 0.000003,
        outputPerToken: 0.000015,
      },
      'tencent/hunyuan-a13b-instruct': {
        inputPerToken: 1.4e-7,
        outputPerToken: 5.7e-7,
      },
      'tngtech/deepseek-r1t2-chimera': {
        inputPerToken: 2.5e-7,
        outputPerToken: 8.5e-7,
      },
      'morph/morph-v3-large': {
        inputPerToken: 9e-7,
        outputPerToken: 0.0000019,
      },
      'morph/morph-v3-fast': {
        inputPerToken: 8e-7,
        outputPerToken: 0.0000012,
      },
      'baidu/ernie-4.5-vl-424b-a47b': {
        inputPerToken: 4.2e-7,
        outputPerToken: 0.00000125,
      },
      'baidu/ernie-4.5-300b-a47b': {
        inputPerToken: 2.8e-7,
        outputPerToken: 0.0000011,
      },
      'inception/mercury': {
        inputPerToken: 2.5e-7,
        outputPerToken: 0.000001,
      },
      'mistralai/mistral-small-3.2-24b-instruct': {
        inputPerToken: 6e-8,
        outputPerToken: 1.8e-7,
      },
      'minimax/minimax-m1': {
        inputPerToken: 4e-7,
        outputPerToken: 0.0000022,
      },
      'google/gemini-2.5-flash': {
        inputPerToken: 3e-7,
        outputPerToken: 0.0000025,
      },
      'google/gemini-2.5-pro': {
        inputPerToken: 0.00000125,
        outputPerToken: 0.00001,
      },
      'moonshotai/kimi-dev-72b': {
        inputPerToken: 2.9e-7,
        outputPerToken: 0.00000115,
      },
      'openai/o3-pro': {
        inputPerToken: 0.00002,
        outputPerToken: 0.00008,
      },
      'x-ai/grok-3-mini': {
        inputPerToken: 3e-7,
        outputPerToken: 5e-7,
      },
      'x-ai/grok-3': {
        inputPerToken: 0.000003,
        outputPerToken: 0.000015,
      },
      'google/gemini-2.5-pro-preview': {
        inputPerToken: 0.00000125,
        outputPerToken: 0.00001,
      },
      'deepseek/deepseek-r1-0528-qwen3-8b': {
        inputPerToken: 6e-8,
        outputPerToken: 9e-8,
      },
      'deepseek/deepseek-r1-0528': {
        inputPerToken: 4e-7,
        outputPerToken: 0.00000175,
      },
      'anthropic/claude-opus-4': {
        inputPerToken: 0.000015,
        outputPerToken: 0.000075,
      },
      'anthropic/claude-sonnet-4': {
        inputPerToken: 0.000003,
        outputPerToken: 0.000015,
      },
      'mistralai/devstral-small-2505': {
        inputPerToken: 6e-8,
        outputPerToken: 1.2e-7,
      },
      'google/gemma-3n-e4b-it': {
        inputPerToken: 2e-8,
        outputPerToken: 4e-8,
      },
      'openai/codex-mini': {
        inputPerToken: 0.0000015,
        outputPerToken: 0.000006,
      },
      'nousresearch/deephermes-3-mistral-24b-preview': {
        inputPerToken: 2e-8,
        outputPerToken: 1e-7,
      },
      'mistralai/mistral-medium-3': {
        inputPerToken: 4e-7,
        outputPerToken: 0.000002,
      },
      'google/gemini-2.5-pro-preview-05-06': {
        inputPerToken: 0.00000125,
        outputPerToken: 0.00001,
      },
      'arcee-ai/spotlight': {
        inputPerToken: 1.8e-7,
        outputPerToken: 1.8e-7,
      },
      'arcee-ai/maestro-reasoning': {
        inputPerToken: 9e-7,
        outputPerToken: 0.0000033,
      },
      'arcee-ai/virtuoso-large': {
        inputPerToken: 7.5e-7,
        outputPerToken: 0.0000012,
      },
      'arcee-ai/coder-large': {
        inputPerToken: 5e-7,
        outputPerToken: 8e-7,
      },
      'microsoft/phi-4-reasoning-plus': {
        inputPerToken: 7e-8,
        outputPerToken: 3.5e-7,
      },
      'inception/mercury-coder': {
        inputPerToken: 2.5e-7,
        outputPerToken: 0.000001,
      },
      'deepseek/deepseek-prover-v2': {
        inputPerToken: 5e-7,
        outputPerToken: 0.00000218,
      },
      'meta-llama/llama-guard-4-12b': {
        inputPerToken: 1.8e-7,
        outputPerToken: 1.8e-7,
      },
      'qwen/qwen3-30b-a3b': {
        inputPerToken: 6e-8,
        outputPerToken: 2.2e-7,
      },
      'qwen/qwen3-8b': {
        inputPerToken: 3.5e-8,
        outputPerToken: 1.38e-7,
      },
      'qwen/qwen3-14b': {
        inputPerToken: 5e-8,
        outputPerToken: 2.2e-7,
      },
      'qwen/qwen3-32b': {
        inputPerToken: 8e-8,
        outputPerToken: 2.4e-7,
      },
      'qwen/qwen3-235b-a22b': {
        inputPerToken: 1.8e-7,
        outputPerToken: 5.4e-7,
      },
      'tngtech/deepseek-r1t-chimera': {
        inputPerToken: 3e-7,
        outputPerToken: 0.0000012,
      },
      'openai/o4-mini-high': {
        inputPerToken: 0.0000011,
        outputPerToken: 0.0000044,
      },
      'openai/o3': {
        inputPerToken: 0.000002,
        outputPerToken: 0.000008,
      },
      'openai/o4-mini': {
        inputPerToken: 0.0000011,
        outputPerToken: 0.0000044,
      },
      'qwen/qwen2.5-coder-7b-instruct': {
        inputPerToken: 3e-8,
        outputPerToken: 9e-8,
      },
      'openai/gpt-4.1': {
        inputPerToken: 0.000002,
        outputPerToken: 0.000008,
      },
      'openai/gpt-4.1-mini': {
        inputPerToken: 4e-7,
        outputPerToken: 0.0000016,
      },
      'openai/gpt-4.1-nano': {
        inputPerToken: 1e-7,
        outputPerToken: 4e-7,
      },
      'eleutherai/llemma_7b': {
        inputPerToken: 8e-7,
        outputPerToken: 0.0000012,
      },
      'alfredpros/codellama-7b-instruct-solidity': {
        inputPerToken: 8e-7,
        outputPerToken: 0.0000012,
      },
      'x-ai/grok-3-mini-beta': {
        inputPerToken: 3e-7,
        outputPerToken: 5e-7,
      },
      'x-ai/grok-3-beta': {
        inputPerToken: 0.000003,
        outputPerToken: 0.000015,
      },
      'nvidia/llama-3.1-nemotron-ultra-253b-v1': {
        inputPerToken: 6e-7,
        outputPerToken: 0.0000018,
      },
      'meta-llama/llama-4-maverick': {
        inputPerToken: 1.5e-7,
        outputPerToken: 6e-7,
      },
      'meta-llama/llama-4-scout': {
        inputPerToken: 8e-8,
        outputPerToken: 3e-7,
      },
      'qwen/qwen2.5-vl-32b-instruct': {
        inputPerToken: 5e-8,
        outputPerToken: 2.2e-7,
      },
      'deepseek/deepseek-chat-v3-0324': {
        inputPerToken: 1.9e-7,
        outputPerToken: 8.7e-7,
      },
      'openai/o1-pro': {
        inputPerToken: 0.00015,
        outputPerToken: 0.0006,
      },
      'mistralai/mistral-small-3.1-24b-instruct': {
        inputPerToken: 3e-8,
        outputPerToken: 1.1e-7,
      },
      'allenai/olmo-2-0325-32b-instruct': {
        inputPerToken: 5e-8,
        outputPerToken: 2e-7,
      },
      'google/gemma-3-4b-it': {
        inputPerToken: 1.703012e-8,
        outputPerToken: 6.81536e-8,
      },
      'google/gemma-3-12b-it': {
        inputPerToken: 3e-8,
        outputPerToken: 1e-7,
      },
      'cohere/command-a': {
        inputPerToken: 0.0000025,
        outputPerToken: 0.00001,
      },
      'openai/gpt-4o-mini-search-preview': {
        inputPerToken: 1.5e-7,
        outputPerToken: 6e-7,
      },
      'openai/gpt-4o-search-preview': {
        inputPerToken: 0.0000025,
        outputPerToken: 0.00001,
      },
      'google/gemma-3-27b-it': {
        inputPerToken: 3.6e-8,
        outputPerToken: 6.4e-8,
      },
      'thedrummer/skyfall-36b-v2': {
        inputPerToken: 5.5e-7,
        outputPerToken: 8e-7,
      },
      'microsoft/phi-4-multimodal-instruct': {
        inputPerToken: 5e-8,
        outputPerToken: 1e-7,
      },
      'perplexity/sonar-reasoning-pro': {
        inputPerToken: 0.000002,
        outputPerToken: 0.000008,
      },
      'perplexity/sonar-pro': {
        inputPerToken: 0.000003,
        outputPerToken: 0.000015,
      },
      'perplexity/sonar-deep-research': {
        inputPerToken: 0.000002,
        outputPerToken: 0.000008,
      },
      'qwen/qwq-32b': {
        inputPerToken: 1.5e-7,
        outputPerToken: 4e-7,
      },
      'google/gemini-2.0-flash-lite-001': {
        inputPerToken: 7.5e-8,
        outputPerToken: 3e-7,
      },
      'anthropic/claude-3.7-sonnet:thinking': {
        inputPerToken: 0.000003,
        outputPerToken: 0.000015,
      },
      'anthropic/claude-3.7-sonnet': {
        inputPerToken: 0.000003,
        outputPerToken: 0.000015,
      },
      'mistralai/mistral-saba': {
        inputPerToken: 2e-7,
        outputPerToken: 6e-7,
      },
      'meta-llama/llama-guard-3-8b': {
        inputPerToken: 2e-8,
        outputPerToken: 6e-8,
      },
      'openai/o3-mini-high': {
        inputPerToken: 0.0000011,
        outputPerToken: 0.0000044,
      },
      'google/gemini-2.0-flash-001': {
        inputPerToken: 1e-7,
        outputPerToken: 4e-7,
      },
      'qwen/qwen-vl-plus': {
        inputPerToken: 2.1e-7,
        outputPerToken: 6.3e-7,
      },
      'aion-labs/aion-1.0': {
        inputPerToken: 0.000004,
        outputPerToken: 0.000008,
      },
      'aion-labs/aion-1.0-mini': {
        inputPerToken: 7e-7,
        outputPerToken: 0.0000014,
      },
      'aion-labs/aion-rp-llama-3.1-8b': {
        inputPerToken: 8e-7,
        outputPerToken: 0.0000016,
      },
      'qwen/qwen-vl-max': {
        inputPerToken: 8e-7,
        outputPerToken: 0.0000032,
      },
      'qwen/qwen-turbo': {
        inputPerToken: 5e-8,
        outputPerToken: 2e-7,
      },
      'qwen/qwen2.5-vl-72b-instruct': {
        inputPerToken: 1.5e-7,
        outputPerToken: 6e-7,
      },
      'qwen/qwen-plus': {
        inputPerToken: 4e-7,
        outputPerToken: 0.0000012,
      },
      'qwen/qwen-max': {
        inputPerToken: 0.0000016,
        outputPerToken: 0.0000064,
      },
      'openai/o3-mini': {
        inputPerToken: 0.0000011,
        outputPerToken: 0.0000044,
      },
      'mistralai/mistral-small-24b-instruct-2501': {
        inputPerToken: 3e-8,
        outputPerToken: 1.1e-7,
      },
      'deepseek/deepseek-r1-distill-qwen-32b': {
        inputPerToken: 2.7e-7,
        outputPerToken: 2.7e-7,
      },
      'deepseek/deepseek-r1-distill-qwen-14b': {
        inputPerToken: 1.5e-7,
        outputPerToken: 1.5e-7,
      },
      'perplexity/sonar-reasoning': {
        inputPerToken: 0.000001,
        outputPerToken: 0.000005,
      },
      'perplexity/sonar': {
        inputPerToken: 0.000001,
        outputPerToken: 0.000001,
      },
      'deepseek/deepseek-r1-distill-llama-70b': {
        inputPerToken: 3e-8,
        outputPerToken: 1.1e-7,
      },
      'deepseek/deepseek-r1': {
        inputPerToken: 7e-7,
        outputPerToken: 0.0000024,
      },
      'minimax/minimax-01': {
        inputPerToken: 2e-7,
        outputPerToken: 0.0000011,
      },
      'microsoft/phi-4': {
        inputPerToken: 6e-8,
        outputPerToken: 1.4e-7,
      },
      'sao10k/l3.1-70b-hanami-x1': {
        inputPerToken: 0.000003,
        outputPerToken: 0.000003,
      },
      'deepseek/deepseek-chat': {
        inputPerToken: 3e-7,
        outputPerToken: 0.0000012,
      },
      'sao10k/l3.3-euryale-70b': {
        inputPerToken: 6.5e-7,
        outputPerToken: 7.5e-7,
      },
      'openai/o1': {
        inputPerToken: 0.000015,
        outputPerToken: 0.00006,
      },
      'cohere/command-r7b-12-2024': {
        inputPerToken: 3.75e-8,
        outputPerToken: 1.5e-7,
      },
      'meta-llama/llama-3.3-70b-instruct': {
        inputPerToken: 1e-7,
        outputPerToken: 3.2e-7,
      },
      'amazon/nova-lite-v1': {
        inputPerToken: 6e-8,
        outputPerToken: 2.4e-7,
      },
      'amazon/nova-micro-v1': {
        inputPerToken: 3.5e-8,
        outputPerToken: 1.4e-7,
      },
      'amazon/nova-pro-v1': {
        inputPerToken: 8e-7,
        outputPerToken: 0.0000032,
      },
      'openai/gpt-4o-2024-11-20': {
        inputPerToken: 0.0000025,
        outputPerToken: 0.00001,
      },
      'mistralai/mistral-large-2411': {
        inputPerToken: 0.000002,
        outputPerToken: 0.000006,
      },
      'mistralai/mistral-large-2407': {
        inputPerToken: 0.000002,
        outputPerToken: 0.000006,
      },
      'mistralai/pixtral-large-2411': {
        inputPerToken: 0.000002,
        outputPerToken: 0.000006,
      },
      'qwen/qwen-2.5-coder-32b-instruct': {
        inputPerToken: 3e-8,
        outputPerToken: 1.1e-7,
      },
      'raifle/sorcererlm-8x22b': {
        inputPerToken: 0.0000045,
        outputPerToken: 0.0000045,
      },
      'thedrummer/unslopnemo-12b': {
        inputPerToken: 4e-7,
        outputPerToken: 4e-7,
      },
      'anthropic/claude-3.5-haiku-20241022': {
        inputPerToken: 8e-7,
        outputPerToken: 0.000004,
      },
      'anthropic/claude-3.5-haiku': {
        inputPerToken: 8e-7,
        outputPerToken: 0.000004,
      },
      'anthracite-org/magnum-v4-72b': {
        inputPerToken: 0.000003,
        outputPerToken: 0.000005,
      },
      'anthropic/claude-3.5-sonnet': {
        inputPerToken: 0.000006,
        outputPerToken: 0.00003,
      },
      'mistralai/ministral-8b': {
        inputPerToken: 1e-7,
        outputPerToken: 1e-7,
      },
      'mistralai/ministral-3b': {
        inputPerToken: 4e-8,
        outputPerToken: 4e-8,
      },
      'qwen/qwen-2.5-7b-instruct': {
        inputPerToken: 4e-8,
        outputPerToken: 1e-7,
      },
      'nvidia/llama-3.1-nemotron-70b-instruct': {
        inputPerToken: 0.0000012,
        outputPerToken: 0.0000012,
      },
      'inflection/inflection-3-pi': {
        inputPerToken: 0.0000025,
        outputPerToken: 0.00001,
      },
      'inflection/inflection-3-productivity': {
        inputPerToken: 0.0000025,
        outputPerToken: 0.00001,
      },
      'thedrummer/rocinante-12b': {
        inputPerToken: 1.7e-7,
        outputPerToken: 4.3e-7,
      },
      'meta-llama/llama-3.2-3b-instruct': {
        inputPerToken: 2e-8,
        outputPerToken: 2e-8,
      },
      'meta-llama/llama-3.2-1b-instruct': {
        inputPerToken: 2.7e-8,
        outputPerToken: 2e-7,
      },
      'meta-llama/llama-3.2-90b-vision-instruct': {
        inputPerToken: 3.5e-7,
        outputPerToken: 4e-7,
      },
      'meta-llama/llama-3.2-11b-vision-instruct': {
        inputPerToken: 4.9e-8,
        outputPerToken: 4.9e-8,
      },
      'qwen/qwen-2.5-72b-instruct': {
        inputPerToken: 1.2e-7,
        outputPerToken: 3.9e-7,
      },
      'neversleep/llama-3.1-lumimaid-8b': {
        inputPerToken: 9e-8,
        outputPerToken: 6e-7,
      },
      'mistralai/pixtral-12b': {
        inputPerToken: 1e-7,
        outputPerToken: 1e-7,
      },
      'cohere/command-r-08-2024': {
        inputPerToken: 1.5e-7,
        outputPerToken: 6e-7,
      },
      'cohere/command-r-plus-08-2024': {
        inputPerToken: 0.0000025,
        outputPerToken: 0.00001,
      },
      'sao10k/l3.1-euryale-70b': {
        inputPerToken: 6.5e-7,
        outputPerToken: 7.5e-7,
      },
      'qwen/qwen-2.5-vl-7b-instruct': {
        inputPerToken: 2e-7,
        outputPerToken: 2e-7,
      },
      'microsoft/phi-3.5-mini-128k-instruct': {
        inputPerToken: 1e-7,
        outputPerToken: 1e-7,
      },
      'nousresearch/hermes-3-llama-3.1-70b': {
        inputPerToken: 3e-7,
        outputPerToken: 3e-7,
      },
      'nousresearch/hermes-3-llama-3.1-405b': {
        inputPerToken: 0.000001,
        outputPerToken: 0.000001,
      },
      'openai/chatgpt-4o-latest': {
        inputPerToken: 0.000005,
        outputPerToken: 0.000015,
      },
      'sao10k/l3-lunaris-8b': {
        inputPerToken: 4e-8,
        outputPerToken: 5e-8,
      },
      'openai/gpt-4o-2024-08-06': {
        inputPerToken: 0.0000025,
        outputPerToken: 0.00001,
      },
      'meta-llama/llama-3.1-405b': {
        inputPerToken: 0.000004,
        outputPerToken: 0.000004,
      },
      'meta-llama/llama-3.1-8b-instruct': {
        inputPerToken: 2e-8,
        outputPerToken: 3e-8,
      },
      'meta-llama/llama-3.1-405b-instruct': {
        inputPerToken: 0.0000035,
        outputPerToken: 0.0000035,
      },
      'meta-llama/llama-3.1-70b-instruct': {
        inputPerToken: 4e-7,
        outputPerToken: 4e-7,
      },
      'mistralai/mistral-nemo': {
        inputPerToken: 2e-8,
        outputPerToken: 4e-8,
      },
      'openai/gpt-4o-mini-2024-07-18': {
        inputPerToken: 1.5e-7,
        outputPerToken: 6e-7,
      },
      'openai/gpt-4o-mini': {
        inputPerToken: 1.5e-7,
        outputPerToken: 6e-7,
      },
      'google/gemma-2-27b-it': {
        inputPerToken: 6.5e-7,
        outputPerToken: 6.5e-7,
      },
      'google/gemma-2-9b-it': {
        inputPerToken: 3e-8,
        outputPerToken: 9e-8,
      },
      'sao10k/l3-euryale-70b': {
        inputPerToken: 0.00000148,
        outputPerToken: 0.00000148,
      },
      'nousresearch/hermes-2-pro-llama-3-8b': {
        inputPerToken: 2.5e-8,
        outputPerToken: 8e-8,
      },
      'mistralai/mistral-7b-instruct': {
        inputPerToken: 2.8e-8,
        outputPerToken: 5.4e-8,
      },
      'mistralai/mistral-7b-instruct-v0.3': {
        inputPerToken: 2e-7,
        outputPerToken: 2e-7,
      },
      'microsoft/phi-3-mini-128k-instruct': {
        inputPerToken: 1e-7,
        outputPerToken: 1e-7,
      },
      'microsoft/phi-3-medium-128k-instruct': {
        inputPerToken: 0.000001,
        outputPerToken: 0.000001,
      },
      'meta-llama/llama-guard-2-8b': {
        inputPerToken: 2e-7,
        outputPerToken: 2e-7,
      },
      'openai/gpt-4o-2024-05-13': {
        inputPerToken: 0.000005,
        outputPerToken: 0.000015,
      },
      'openai/gpt-4o': {
        inputPerToken: 0.0000025,
        outputPerToken: 0.00001,
      },
      'meta-llama/llama-3-70b-instruct': {
        inputPerToken: 3e-7,
        outputPerToken: 4e-7,
      },
      'meta-llama/llama-3-8b-instruct': {
        inputPerToken: 3e-8,
        outputPerToken: 6e-8,
      },
      'mistralai/mixtral-8x22b-instruct': {
        inputPerToken: 0.000002,
        outputPerToken: 0.000006,
      },
      'microsoft/wizardlm-2-8x22b': {
        inputPerToken: 4.8e-7,
        outputPerToken: 4.8e-7,
      },
      'openai/gpt-4-turbo': {
        inputPerToken: 0.00001,
        outputPerToken: 0.00003,
      },
      'anthropic/claude-3-haiku': {
        inputPerToken: 2.5e-7,
        outputPerToken: 0.00000125,
      },
      'anthropic/claude-3-opus': {
        inputPerToken: 0.000015,
        outputPerToken: 0.000075,
      },
      'mistralai/mistral-large': {
        inputPerToken: 0.000002,
        outputPerToken: 0.000006,
      },
      'openai/gpt-3.5-turbo-0613': {
        inputPerToken: 0.000001,
        outputPerToken: 0.000002,
      },
      'openai/gpt-4-turbo-preview': {
        inputPerToken: 0.00001,
        outputPerToken: 0.00003,
      },
      'mistralai/mistral-tiny': {
        inputPerToken: 2.5e-7,
        outputPerToken: 2.5e-7,
      },
      'mistralai/mistral-7b-instruct-v0.2': {
        inputPerToken: 2e-7,
        outputPerToken: 2e-7,
      },
      'mistralai/mixtral-8x7b-instruct': {
        inputPerToken: 5.4e-7,
        outputPerToken: 5.4e-7,
      },
      'neversleep/noromaid-20b': {
        inputPerToken: 0.000001,
        outputPerToken: 0.00000175,
      },
      'alpindale/goliath-120b': {
        inputPerToken: 0.000006,
        outputPerToken: 0.000008,
      },
      'openrouter/auto': {
        inputPerToken: -1,
        outputPerToken: -1,
      },
      'openai/gpt-4-1106-preview': {
        inputPerToken: 0.00001,
        outputPerToken: 0.00003,
      },
      'openai/gpt-3.5-turbo-instruct': {
        inputPerToken: 0.0000015,
        outputPerToken: 0.000002,
      },
      'mistralai/mistral-7b-instruct-v0.1': {
        inputPerToken: 1.1e-7,
        outputPerToken: 1.9e-7,
      },
      'openai/gpt-3.5-turbo-16k': {
        inputPerToken: 0.000003,
        outputPerToken: 0.000004,
      },
      'mancer/weaver': {
        inputPerToken: 7.5e-7,
        outputPerToken: 0.000001,
      },
      'undi95/remm-slerp-l2-13b': {
        inputPerToken: 4.5e-7,
        outputPerToken: 6.5e-7,
      },
      'gryphe/mythomax-l2-13b': {
        inputPerToken: 6e-8,
        outputPerToken: 6e-8,
      },
      'openai/gpt-4-0314': {
        inputPerToken: 0.00003,
        outputPerToken: 0.00006,
      },
      'openai/gpt-4': {
        inputPerToken: 0.00003,
        outputPerToken: 0.00006,
      },
      'openai/gpt-3.5-turbo': {
        inputPerToken: 5e-7,
        outputPerToken: 0.0000015,
      },
    },
  },
};
