/**
 * Static pricing cache - bundled with extension for offline/privacy mode
 * 
 * This file is auto-generated by scripts/generate-pricing-cache.ts
 * Run: pnpm generate-pricing-cache
 * 
 * When useLivePricingData is false, the extension uses this cached data
 * instead of making external API calls to Helicone and OpenRouter.
 */

export interface CachedProviderData {
  models: string[];
  pricing: Record<string, { inputPerToken: number; outputPerToken: number }>;
}

export interface CachedOpenRouterGroup {
  id: string;
  displayName: string;
  models: string[];
}

export interface CachedPricingData {
  generatedAt: string;
  version: number;
  helicone: Record<string, CachedProviderData>;
  openRouter: {
    groups: CachedOpenRouterGroup[];
    pricing: Record<string, { inputPerToken: number; outputPerToken: number }>;
  };
}

// Cache generated on 2024-12-11 - Update by running: pnpm generate-pricing-cache
export const CACHED_PRICING_DATA: CachedPricingData = {
  generatedAt: '2024-12-11T00:00:00.000Z',
  version: 1,
  helicone: {
    openai: {
      models: [
        'gpt-4o', 'gpt-4o-mini', 'gpt-4o-2024-11-20', 'gpt-4o-2024-08-06',
        'gpt-4o-mini-2024-07-18', 'gpt-4-turbo', 'gpt-4-turbo-preview',
        'gpt-4', 'gpt-3.5-turbo', 'o1', 'o1-mini', 'o1-preview',
        'gpt-4.1', 'gpt-4.1-mini', 'gpt-4.1-nano',
        'gpt-4o-search-preview', 'gpt-4o-mini-search-preview',
      ],
      pricing: {
        'gpt-4o': { inputPerToken: 2.5e-6, outputPerToken: 10e-6 },
        'gpt-4o-mini': { inputPerToken: 0.15e-6, outputPerToken: 0.6e-6 },
        'gpt-4o-2024-11-20': { inputPerToken: 2.5e-6, outputPerToken: 10e-6 },
        'gpt-4o-2024-08-06': { inputPerToken: 2.5e-6, outputPerToken: 10e-6 },
        'gpt-4o-mini-2024-07-18': { inputPerToken: 0.15e-6, outputPerToken: 0.6e-6 },
        'gpt-4-turbo': { inputPerToken: 10e-6, outputPerToken: 30e-6 },
        'gpt-4-turbo-preview': { inputPerToken: 10e-6, outputPerToken: 30e-6 },
        'gpt-4': { inputPerToken: 30e-6, outputPerToken: 60e-6 },
        'gpt-3.5-turbo': { inputPerToken: 0.5e-6, outputPerToken: 1.5e-6 },
        'o1': { inputPerToken: 15e-6, outputPerToken: 60e-6 },
        'o1-mini': { inputPerToken: 3e-6, outputPerToken: 12e-6 },
        'o1-preview': { inputPerToken: 15e-6, outputPerToken: 60e-6 },
        'gpt-4.1': { inputPerToken: 2e-6, outputPerToken: 8e-6 },
        'gpt-4.1-mini': { inputPerToken: 0.4e-6, outputPerToken: 1.6e-6 },
        'gpt-4.1-nano': { inputPerToken: 0.1e-6, outputPerToken: 0.4e-6 },
        'gpt-4o-search-preview': { inputPerToken: 2.5e-6, outputPerToken: 10e-6 },
        'gpt-4o-mini-search-preview': { inputPerToken: 0.15e-6, outputPerToken: 0.6e-6 },
      },
    },
    anthropic: {
      models: [
        'claude-3-5-sonnet-latest', 'claude-3-5-sonnet-20241022',
        'claude-3-5-haiku-latest', 'claude-3-5-haiku-20241022',
        'claude-3-opus-20240229', 'claude-3-sonnet-20240229', 'claude-3-haiku-20240307',
        'claude-sonnet-4-20250514', 'claude-sonnet-4-0',
        'claude-opus-4-20250514', 'claude-opus-4-0',
      ],
      pricing: {
        'claude-3-5-sonnet-latest': { inputPerToken: 3e-6, outputPerToken: 15e-6 },
        'claude-3-5-sonnet-20241022': { inputPerToken: 3e-6, outputPerToken: 15e-6 },
        'claude-3-5-haiku-latest': { inputPerToken: 0.8e-6, outputPerToken: 4e-6 },
        'claude-3-5-haiku-20241022': { inputPerToken: 0.8e-6, outputPerToken: 4e-6 },
        'claude-3-opus-20240229': { inputPerToken: 15e-6, outputPerToken: 75e-6 },
        'claude-3-sonnet-20240229': { inputPerToken: 3e-6, outputPerToken: 15e-6 },
        'claude-3-haiku-20240307': { inputPerToken: 0.25e-6, outputPerToken: 1.25e-6 },
        'claude-sonnet-4-20250514': { inputPerToken: 3e-6, outputPerToken: 15e-6 },
        'claude-sonnet-4-0': { inputPerToken: 3e-6, outputPerToken: 15e-6 },
        'claude-opus-4-20250514': { inputPerToken: 15e-6, outputPerToken: 75e-6 },
        'claude-opus-4-0': { inputPerToken: 15e-6, outputPerToken: 75e-6 },
      },
    },
    gemini: {
      models: [
        'gemini-2.0-flash', 'gemini-2.0-flash-lite',
        'gemini-1.5-pro', 'gemini-1.5-flash', 'gemini-1.5-flash-8b',
        'gemini-2.5-flash', 'gemini-2.5-pro', 'gemini-2.5-flash-lite',
      ],
      pricing: {
        'gemini-2.0-flash': { inputPerToken: 0.1e-6, outputPerToken: 0.4e-6 },
        'gemini-2.0-flash-lite': { inputPerToken: 0.075e-6, outputPerToken: 0.3e-6 },
        'gemini-1.5-pro': { inputPerToken: 1.25e-6, outputPerToken: 5e-6 },
        'gemini-1.5-flash': { inputPerToken: 0.075e-6, outputPerToken: 0.3e-6 },
        'gemini-1.5-flash-8b': { inputPerToken: 0.0375e-6, outputPerToken: 0.15e-6 },
        'gemini-2.5-flash': { inputPerToken: 0.15e-6, outputPerToken: 0.6e-6 },
        'gemini-2.5-pro': { inputPerToken: 1.25e-6, outputPerToken: 10e-6 },
        'gemini-2.5-flash-lite': { inputPerToken: 0.075e-6, outputPerToken: 0.3e-6 },
      },
    },
    grok: {
      models: ['grok-2', 'grok-2-mini', 'grok-beta', 'grok-3', 'grok-3-fast', 'grok-3-mini', 'grok-3-mini-fast'],
      pricing: {
        'grok-2': { inputPerToken: 2e-6, outputPerToken: 10e-6 },
        'grok-2-mini': { inputPerToken: 0.2e-6, outputPerToken: 1e-6 },
        'grok-beta': { inputPerToken: 5e-6, outputPerToken: 15e-6 },
        'grok-3': { inputPerToken: 3e-6, outputPerToken: 15e-6 },
        'grok-3-fast': { inputPerToken: 5e-6, outputPerToken: 25e-6 },
        'grok-3-mini': { inputPerToken: 0.3e-6, outputPerToken: 0.5e-6 },
        'grok-3-mini-fast': { inputPerToken: 0.6e-6, outputPerToken: 4e-6 },
      },
    },
  },
  openRouter: {
    groups: [
      { id: 'openai', displayName: 'OpenAI', models: ['openai/gpt-4o', 'openai/gpt-4o-mini', 'openai/gpt-4-turbo', 'openai/gpt-4.1', 'openai/gpt-4.1-mini', 'openai/o1', 'openai/o1-mini'] },
      { id: 'anthropic', displayName: 'Anthropic', models: ['anthropic/claude-3.5-sonnet', 'anthropic/claude-3-haiku', 'anthropic/claude-3-opus'] },
      { id: 'google', displayName: 'Google', models: ['google/gemini-2.0-flash', 'google/gemini-1.5-pro', 'google/gemini-1.5-flash', 'google/gemini-2.5-flash-preview'] },
      { id: 'meta-llama', displayName: 'Meta Llama', models: ['meta-llama/llama-3.1-405b-instruct', 'meta-llama/llama-3.1-70b-instruct', 'meta-llama/llama-3.1-8b-instruct'] },
      { id: 'mistralai', displayName: 'Mistral', models: ['mistralai/mixtral-8x7b-instruct', 'mistralai/mistral-7b-instruct', 'mistralai/mistral-large'] },
      { id: 'x-ai', displayName: 'xAI', models: ['x-ai/grok-2', 'x-ai/grok-beta'] },
      { id: 'deepseek', displayName: 'DeepSeek', models: ['deepseek/deepseek-chat', 'deepseek/deepseek-coder'] },
    ],
    pricing: {
      'openai/gpt-4o': { inputPerToken: 2.5e-6, outputPerToken: 10e-6 },
      'openai/gpt-4o-mini': { inputPerToken: 0.15e-6, outputPerToken: 0.6e-6 },
      'openai/gpt-4-turbo': { inputPerToken: 10e-6, outputPerToken: 30e-6 },
      'openai/gpt-4.1': { inputPerToken: 2e-6, outputPerToken: 8e-6 },
      'openai/gpt-4.1-mini': { inputPerToken: 0.4e-6, outputPerToken: 1.6e-6 },
      'openai/o1': { inputPerToken: 15e-6, outputPerToken: 60e-6 },
      'openai/o1-mini': { inputPerToken: 3e-6, outputPerToken: 12e-6 },
      'anthropic/claude-3.5-sonnet': { inputPerToken: 3e-6, outputPerToken: 15e-6 },
      'anthropic/claude-3-haiku': { inputPerToken: 0.25e-6, outputPerToken: 1.25e-6 },
      'anthropic/claude-3-opus': { inputPerToken: 15e-6, outputPerToken: 75e-6 },
      'google/gemini-2.0-flash': { inputPerToken: 0.1e-6, outputPerToken: 0.4e-6 },
      'google/gemini-1.5-pro': { inputPerToken: 1.25e-6, outputPerToken: 5e-6 },
      'google/gemini-1.5-flash': { inputPerToken: 0.075e-6, outputPerToken: 0.3e-6 },
      'google/gemini-2.5-flash-preview': { inputPerToken: 0.15e-6, outputPerToken: 0.6e-6 },
      'meta-llama/llama-3.1-405b-instruct': { inputPerToken: 2.7e-6, outputPerToken: 2.7e-6 },
      'meta-llama/llama-3.1-70b-instruct': { inputPerToken: 0.52e-6, outputPerToken: 0.75e-6 },
      'meta-llama/llama-3.1-8b-instruct': { inputPerToken: 0.055e-6, outputPerToken: 0.055e-6 },
      'mistralai/mixtral-8x7b-instruct': { inputPerToken: 0.24e-6, outputPerToken: 0.24e-6 },
      'mistralai/mistral-7b-instruct': { inputPerToken: 0.055e-6, outputPerToken: 0.055e-6 },
      'mistralai/mistral-large': { inputPerToken: 2e-6, outputPerToken: 6e-6 },
      'x-ai/grok-2': { inputPerToken: 2e-6, outputPerToken: 10e-6 },
      'x-ai/grok-beta': { inputPerToken: 5e-6, outputPerToken: 15e-6 },
      'deepseek/deepseek-chat': { inputPerToken: 0.14e-6, outputPerToken: 0.28e-6 },
      'deepseek/deepseek-coder': { inputPerToken: 0.14e-6, outputPerToken: 0.28e-6 },
    },
  },
};

